### ISSUE TITLE
Configurable balance  - nieprawidłowe zliczanie 

### ISSUE THREAD

**Issue by dariuszszwajcok** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#102]
Zawuważyłem dziś u siebie dziwne zachowanie tj:
oddanie 3032kWh
pobrano 2582kWh
bilans    -450

Wynika z tego że nie wzieło pod uwage wspołczynnika 0,8
Wg mojego przelicznika wychodzi mi:
oddano 3032               x 0,8 = 2425kWh
pobranno 2582
bilans -157

Ale jest też jedna dziwna rzecz mianowicie z powodu problemów huawei z oprogramowaniem optymalizatorow produkcja wynosi  0 kWh, zatem w ciągu ostatniej doby miałem:
oddanie 0 kWh
pobranie 14,6 kWh
bilans po przeliczeniu z wczorajszego dnia zmienił się z  UWAGA  z  -465,3  na  -450,9 kWh.  Wynika z tego że zamiast pobrać 14,6 to je oddałem...   dni poprzednie tez wygladały podobnie bo dwa dni temu mialem bilans -478 kWh nie oddając nic do sieci tylko pobierając.

state_class: total
tariff: G11
sum_consumption: 2131.325
sum_generation: -2582.298                   <------------------------  czy tutaj nie powinna być wartość dodatnia?
data_range: 2022-04-01 - 2023-01-27
cała doba_consumption: 2131.325
cała doba_generation: -2582.298
unit_of_measurement: kWh
device_class: energy
icon: mdi:counter
friendly_name: Tauron AMIplus Axzyxzyxzyxz  Configurable balance

Czy tylko ja tak mam ze nie sprowadza mi wartości oddanej do 80%?
Czy też miał ktoś problem z naliczaniem bilansu jak u mnie?
z góry dzieki za pomoc

_Originally posted by @dariuszszwajcok in https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/discussions/63#discussioncomment-4805928_

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/100
