### ISSUE TITLE
Literówka w L14 custom_components/tauron_amiplus/translations/pl.json

### ISSUE THREAD

**Issue by IoTNoob** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#103]
Siemanko
wkradla sie literówka w Home-Assistant-custom-components-Tauron-AMIplus/tree/master/custom_components/tauron_amiplus/translations)/pl.json

Mamy:
          "show_configurable_sensors": "Włącz konfugurowalne sensory",
Chyba chodziło o:
          "show_configurable_sensors": "Włącz konfigurowalne sensory",

Zrobilem comita:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/commit/238c50c8d185541a338f5de27b853be162bb80ba

Elo

**Comment by PiotrMachowski** [comment]
Naprawione w v2.4.7
