### ISSUE TITLE
Dwa Liczniki pod jednym kontem w tauronie 

### ISSUE THREAD

**Issue by beny1983** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#105]
Witam,
mam dwa liczniki w 2 różnych lokalizacjach pod jednym kontem e-licznik. Pomimo że wpisuje ID licznika jednego albo drugiego to zawsze pobiera mi dane z licznika na którym jako pierwszy podpisałem umowę z tauronem. Czy to może być problem w Tauronie?

**Comment by PiotrMachowski** [comment]
Możliwe, że nazwa licznika wysyłana do eLicznika się różni od tej, którą podałeś. Spróbuj tak:
- otwórz eLicznik
- zaloguj się
- włącz tryb deweloperski w przeglądarce (`[F12]`)
- przejdź do zakładki "Network"
- w polu "Filter" wpisz `ustaw_punkt`
- zmień aktualny licznik
- powinna się pojawić pozycja na liście, kliknij na nią i otwórz zakładkę "Payload" - tutaj powinien być widoczny nr licznika
- jeszcze raz zmień licznik i sprawdź nr dla pierwszego licznika

**Comment by beny1983** [comment]
Witam, 
pojawia mi się taki nr:
![image](https://user-images.githubusercontent.com/44005362/216326245-76334dd1-e2ab-4fcb-876f-55b23a69dbd4.png)
przy drugim liczniku 
![image](https://user-images.githubusercontent.com/44005362/216326546-faa6fb19-3912-4a78-9177-b9ac58cc7c85.png)
ale w żaden sposób nie odpowiadają te liczby id licznika

**Comment by PiotrMachowski** [comment]
Ok, ale jak ich użyjesz to działa?

**Comment by beny1983** [comment]
Tak dzieła!! 
Wielkie dzięki!!

**Comment by pzol** [comment]
Jakby ktos szukal - wartosci sa w HTML strony
<select name="site[client]" tabindex="-1" class="selectized" style="display: none;">
</select>

**Comment by PiotrMachowski** [comment]
@pzol a są jakoś ładnie połączone z numerami widocznymi w interfejsie?

**Comment by PiotrMachowski** [comment]
@beny1983 Dodaję do integracji interfejs do wybierania licznika, ale nie mam jak go testować, bo mam tylko jeden licznik. Istnieje szansa na podzielenie się danymi logowania?
