### ISSUE TITLE
Więcej jak 1 PPE per konto

### ISSUE THREAD

**Issue by jchrzaniuk** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#106]
Mam pod jedno konto w eLicznik podpięte 2 PPE.
Wygląda na to, że taki przypadek nie nie jest brany pod uwagę. Skrypty pobierają dane jedynie dla pierwszego PPE (mniejsze ID?), niezależnie który numer licznika zostanie wpisany.
Skrypt przyjmuje również numery liczników typu "alamakota"
![obraz](https://user-images.githubusercontent.com/25979170/216976229-f0768548-4de4-47f0-91ca-147702af7d7b.png)

**Comment by PiotrMachowski** [comment]
Duplikat #105 - sytuacja jest brana pod uwagę, ale trzeba znaleźć odpowiedni nr. W przeciwnym wypadku zawsze wybierany jest domyślny licznik

**Comment by PiotrMachowski** [comment]
@jchrzaniuk Dodaję do integracji interfejs do wybierania licznika, ale nie mam jak go testować, bo mam tylko jeden licznik. Istnieje szansa na podzielenie się danymi logowania?
