### ISSUE TITLE
Możliwy błąd w konfiguracji sensora

### ISSUE THREAD

**Issue by uowiec** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#107]
Cześć Piotr, dzięki za świetną robotę!
Dziś zauważyłem taki warning, nie wiem na ile jest istotny. Proszą żeby poinformować autora, więc informuję :)

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.tauron_amiplus_590xxxxxxxxxxxxx_daily_energy_generation (<class 'custom_components.tauron_amiplus.sensor.TauronAmiplusConfigFlowSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Home Assistant 2023.2.1
Interfejs użytkownika: 20230202.0 - latest

**Comment by PiotrMachowski** [comment]
Naprawione w v2.4.7
