### ISSUE TITLE
Bilansowanie godzinowe w zakladce Energia i maly rozjazd

### ISSUE THREAD

**Issue by Jordan87** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#118]
Hej

Zauwazylem dziwna rzecz. W zakladce energia korzystam z bilansowania godzinowego.
![image](https://user-images.githubusercontent.com/10414918/227608481-aa966466-f502-4441-9ef6-71971aef3a2f.png)
Niezaleznie czy wybiore okres dzien, tydzien czy miesiac to ucina jedna godzine, dzien, tydzien lub miesiac i dodaje statystyke jednej godziny z kolejnego okresu i miesza cos z pierwszym slupkiem wykresu.
![image](https://user-images.githubusercontent.com/10414918/227609133-cf12c4c0-94df-4cf2-b826-f3a15c297296.png)
![image](https://user-images.githubusercontent.com/10414918/227609384-90046f11-1fc8-4c1c-aa3c-4ad6949a2c35.png)
![image](https://user-images.githubusercontent.com/10414918/227609568-9c006216-983c-413d-a3b7-50e2d99cae4e.png)
Da rade cos z tym zrobic? To chyba nie jest wina samego HA tylko tego ze ta statystyka zawiera zawsze godzine 0:00-1:00 dnia nastepnego.

Dzieki I sorry za kolejne marudzenie zwiazane z bilansowaniem :)

**Comment by Jordan87** [comment]
Tak, panel Energia.
Z tego co widze nie tylko przy bilansowanej.
Strefy raczej sa ok, Poniedzialek jako pierwszy dzien tygodnia.
Jestem aktualnie w USA a serwer w Polsce wiec jest jakas mala szansa ze cos mu odwala z tego powodu. Jak wroce do domu to odpale kompa w polsce i z niego zaladuje aby sprawdzic ale chyba juz w polsce widzialem tam to dziwne wyswietlanie.

**Comment by PiotrMachowski** [comment]
A sprawdzałeś inne encje (nie z mojej integracji)?

**Comment by Jordan87** [comment]
Czy masz na mysli wykresy panelu energia ale z innych encji?
Tez wyswietla okrez bez pierwszego slupka, ale za to nie pokazuje nic w ostatnim "dodatkowym" tak jak w przypadku encji AMI Taurona.
![image](https://user-images.githubusercontent.com/10414918/227656991-3a114c7d-cbd7-4e39-b7ba-cb6fc165d462.png)
![image](https://user-images.githubusercontent.com/10414918/227656922-a3bfb23a-24de-4ae2-a9ac-719c7e979794.png)

**Comment by PiotrMachowski** [comment]
Szczerze mówiąc wygląda mi to na rozjeżdżające się timezony, daj znać, czy sytuacja się ogarnie jak wrócisz do Polski

**Comment by Jordan87** [comment]
Mam w polsce PCta z ktorym moge odpalic zdalny pulpit wiec on siedzi w tej samej strefie co serwer na 100% (sprawdzilem zmiane czasu z tego weekendu).
Wyglada prawie identycznie, brakuje tez jednego dnia np w lutym lub miesiaca w styczniu.
Prawie identycznie do dlupki sa przesuniete o jeden dzien, jak najade myszka na dzien drugiego lutego to pokazuje ze to pierwszy luty wedlug opisu.
![image](https://user-images.githubusercontent.com/10414918/227843257-9aeb3077-1bb0-46e5-a944-5cbc78d6c6ea.png)
![image](https://user-images.githubusercontent.com/10414918/227843502-027d3bc7-7843-46ee-b065-ad2dfbce6374.png)
Mam nieodparte wrażenie ze jest to związane z jedna godzina 0:00-1:00 z twojego dodatku które zawsze jest wyświetlana dodatkowo.

**Comment by Jordan87** [comment]
Gdzie w dev toolsach to mozna uzyc?

**Comment by PiotrMachowski** [comment]
Szablon:
[![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/)

**Comment by Jordan87** [comment]
Dev tools
![image](https://user-images.githubusercontent.com/10414918/228043808-1a502d48-1420-4e14-959f-3aab68ee916b.png)

Konsola
![image](https://user-images.githubusercontent.com/10414918/228043626-e776c8b0-03ad-4da8-8d40-482ba43285c2.png)

**Comment by PiotrMachowski** [comment]
Jaką wersję HA masz?

**Comment by Jordan87** [comment]
Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Interfejs użytkownika: 20230309.1 - latest

**Comment by Jordan87** [comment]
Jesli to cos da moge znow ci udostepnic dostep do mojej platformy eLicznik abyc zaciagnal moje dane i sprawdzil czy bedzie tobie tez tak nieprawidłowo wyświetlał.

**Comment by PiotrMachowski** [comment]
Możemy spróbować :)

**Comment by PiotrMachowski** [comment]
@luciust żadnej :D dane są wrzucane bezpośrednio do statystyk (bo do encji się nie da wrzucić danych historycznych). Nie wiem, czy do Grafany można wrzucić dane ze statystyk, bo nigdy się w to nie bawiłem. Statystyki możesz znaleźć w dev toolsach, wyszukując `tauron_importer`

[![Open your Home Assistant instance and show your statistics developer tools.](https://my.home-assistant.io/badges/developer_statistics.svg)](https://my.home-assistant.io/redirect/developer_statistics/)

**Comment by luciust** [comment]
Hmm... Dzięki spróbuję. Dostałem już nową wersję licznika od lutego i muszę zmienić sposób poboru danych :)

**Comment by PiotrMachowski** [comment]
Właśnie nie jestem przekonany, bo te statystyki nie są podpięte pod żadne sensory.

Tak czy siak, nie przejmujmy wątku, jak coś Ci się uda/będziesz miał jakies pytania, to załóż proszę [osobną dyskusję](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/discussions).

**Comment by PiotrMachowski** [comment]
@Jordan87 Jak sytuacja wygląda aktualnie?

**Comment by Jordan87** [comment]
Za tydzień wracam do Polski to będę dalej badał temat.
Aktualnie jeszcze mi dodatek nie działa i mam wrażenie że gryzie się z dodatkiem Huawei do falownika bo oba nie działają od aktualizacji ale jeszcze nie miałem czasu tego przeglądać.

**Comment by Jordan87** [comment]
Wyglada na to ze problem byl powiazany z sama przegladarka Chrome, tylko dziwne jest to ze na dwoch roznych komputerach jak sie logowalem tak "deformowal" dane z zakladki energia. Zauwazylem teraz ze na Firefox jets ok. Czyszczenie ciastek nie pomagalo wiec uzylem funkcji Zresetuj ustawienia"
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/10414918/f6761ecb-8cb5-4ddb-92fb-7a8b83c4b542)

Narazie jest ok, gdyby problem wrocil za jakis czas bede sprawdzal czy to czasem nie jakis dodatek w Chrome psuje to wyswietlanie.

Dzieki za poswiecony czas, moze komos rowniez pomoze ten watek.

**Comment by PiotrMachowski** [comment]
O, ciekawy przypadek. Dzięki za podzielenie się rozwiązaniem
