### ISSUE TITLE
Integracja nie działa z licznikami w taryfie G11

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#127]
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: 09:11:16 (4 occurrences)
Last logged: 11:37:12

Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...tasks.py:475]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.10/asyncio/futures.py:379
Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...ask_wakeup()]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.10/asyncio/futures.py:379
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 381, in _set_state
    _copy_future_state(other, future)
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 357, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```

**Comment by PiotrMachowski** [comment]
Fixed in `v2.4.9`

**Comment by prezes210** [comment]
Śmiga jak złoto na G11

**Comment by pkordal** [comment]
U mnie standardowe sensory działają, ale nawet bez zaznaczenia 12 miesięcznego zakresu i konfigurowanego nie wpadają wartości bilansowania dziennego. Nawet po godzinie. 

Może poniższy błąd ma z tym związek?

```
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/sensor.py:233 
Integration: Tauron AMIplus (documentation, issues) 
First occurred: 18:22:53 (2 occurrences) 
Last logged: 20:11:14

Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.tauron_amiplus.coordinator.TauronAmiplusUpdateCoordinator object at 0x7f6b21dc30>>
Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.tauron_amiplus.coordinator.TauronAmiplusUpdateCoordinator object at 0x7f6838a410>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 111, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 154, in _handle_coordinator_update
    self.update_balanced_data(data.balance_daily, data.tariff)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 193, in update_balanced_data
    balance, sum_consumption, sum_generation, zones, data_range = TauronAmiplusSensor.get_balanced_data(con, gen)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 233, in get_balanced_data
    zone = zone_names[consumption["Zone"]]
KeyError: 'cała doba'

```

**Comment by mmarcines** [comment]
U mnie też brakuje wartości dla kilku encji. Minęło już jakieś 20 minut.
Poczekam do jutra. Niestety na długi weekend nie zabrałem laptopa a z
telefonu nie za bardzo mam ja logi pobrac.

niedz., 30 kwi 2023, 20:22 użytkownik Paweł Kordal ***@***.***>
napisał:

**Comment by PiotrMachowski** [comment]
@PiotrMachowski dla jakich?

**Comment by mmarcines** [comment]
![Uploading Screenshot_20230430-211759.png…]()

**Comment by mmarcines** [comment]
![Uploading Screenshot_20230430-211759.png…]()

**Comment by mmarcines** [comment]
Configurable balance
Configurable energy consumption
Configurable energy generation
Current consumption reading
Current generation reading
Daily balance
Last 12  months
Monthly balance

**Comment by PiotrMachowski** [comment]
Issue na dane zbalansowane: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/129

**Comment by PiotrMachowski** [comment]
Iiiii naprawione w [v2.4.10](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.4.10)

**Comment by mmarcines** [comment]
Hejo,

v2.4.10 wszystkie encje się mi wczytaly za wyjątkiem tych dwóch
Current generation reading
Current consumption reading

Ktoś ma tak samo?





pon., 1 maj 2023, 02:39 użytkownik Piotr Machowski ***@***.***>
napisał:

**Comment by pkordal** [comment]
Ogromne dzięki @PiotrMachowski

**Comment by krzyzak44** [comment]
Dzień dobry,
a ja się bawiłem, bawiłem i... mam bana na 8h :)


pon., 1 maj 2023, 07:43 użytkownik mmarcines ***@***.***>
napisał:

**Comment by djg-io** [comment]
Przepraszam ale nadal nie rozumiem, które encje podać w dashboard Energia. Które dla Produkcja do sieci a które **Produkcja do sieci**? Wielkie dzięki za pomoc.

**Comment by PiotrMachowski** [comment]
@djg-io musisz wybrać z listy pozycje "tauron_importer" zamiast encji

**Comment by djg-io** [comment]
Nie mam takiej pozycji na liście:( Mam tylko encje zaczynające się Tauron
AMIplus nr punku poboru itd.


wt., 2 maj 2023 o 12:18 Piotr Machowski ***@***.***>
napisał(a):

**Comment by PiotrMachowski** [comment]
@djg-io szukaj dalej, muszą być. Jeśli by nie było, to by encji też nie było. Jeśli będziesz miał dalej problemy, to załóż osobną dyskusję, żeby tutaj nie robić offtopa

**Comment by PiotrMachowski** [comment]
@mmarcines a zobacz, czy w eLiczniku masz odczyty

**Comment by mmarcines** [comment]
Faktycznie od 21 kwietnia dla każdego dnia mam brak danych w elicznik dla
Licznik energii oddanej i Licznik energii pobranej.

Ktoś ma jeszcze podobnie czy jestem osamotniony?

Marcin

śr., 3 maj 2023, 00:04 użytkownik Piotr Machowski ***@***.***>
napisał:
