### ISSUE TITLE
Brak pozycji tauron_importer

### ISSUE THREAD

**Issue by djg-io** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#132]
Jak w temacie.  Na liście rozwijanej w dashboard energia brak pozycji tauron_importer.
![image](https://user-images.githubusercontent.com/614628/235660207-933e8786-df0d-4e8f-960e-f446e614b37a.png)

**Comment by PiotrMachowski** [comment]
Mówiłem, że to nie encja 😉 . Tekst `tauron_importer` jest widoczny w ID poniżej nazwy, na liście w panelu Energia, nie widać tych pozycji na liście encji

**Comment by teh2wsx** [comment]
Przepraszam za odkopanie tematu, ale czy da się zmienić wyświetlaną nazwę `tauron_importer`?

**Comment by PiotrMachowski** [comment]
@teh2wsx nie,  nie da się
