### ISSUE TITLE
2.4.10: KeyError: 'tauron_importer:<TUTAJ_PUNKT_POBORU>_consumption'

### ISSUE THREAD

**Issue by belkone** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#133]
Cześć, 

jako że przestała mi jakiś czas temu również działać integracja to śledziłem ostatnie zgłoszenia i poprawki - niestety dalej pomimo najnowszej wersji, mam problem - wszystkie encje dotyczące integracji niedostępne.
Jedyny log jaki się łapie to:

```
Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/statistics.py:61 
Integration: Tauron AMIplus (documentation, issues) 
First occurred: 09:35:34 (2 occurrences) 
Last logged: 09:35:51

Unexpected error fetching tauron_amiplus data: 'tauron_importer:<TUTAJ_PUNKT_POBORU>_consumption'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 31, in _async_update_data
    await self.generate_statistics(data)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 37, in generate_statistics
    await statistics_updater.update_all(data)
  File "/config/custom_components/tauron_amiplus/statistics.py", line 61, in update_all
    v["sum"] = stat[s][0]["sum"]
KeyError: 'tauron_importer:<TUTAJ_PUNKT_POBORU>_consumption'
```

Oczywiście próbowałem przeinstalowywać, restartować HA w międzyczasie, instalować starsze wersje etc.
Sam eLicznik - aplikacja jak i poprzez stronę działa w porządku.
Tutaj jeszcze informacje o HA:
```
Home Assistant 2023.5.0
Supervisor 2023.04.1
Operating System 10.1
Interfejs użytkownika: 20230503.1 - latest
```

Wersja integracji: 2.4.10
Taryfa: G11

**Comment by PiotrMachowski** [comment]
Hej, jakie masz znaki w punkcie poboru?

**Comment by belkone** [comment]
punkt poboru składa się z samych cyfr, dokładnie 18 znaków :)

**Comment by PiotrMachowski** [comment]
A włącz debugowanie i zobacz, czy dane są pobierane prawidłowo

**Comment by belkone** [comment]
wygląda na to, że coś pobiera :) w załączniku debug log:
[config_entry-tauron_amiplus-dd8009cbb999085f70bb26a3abc7fb2a.json.txt](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/files/11396133/config_entry-tauron_amiplus-dd8009cbb999085f70bb26a3abc7fb2a.json.txt)

**Comment by PiotrMachowski** [comment]
To akurat są dane diagnostyczne, a nie debug log ;) ale faktycznie pobiera dane.

Z kiedy masz ostatnie dane w panelu energia?

**Comment by belkone** [comment]
A racja, w załączniku debug log :) 
[home-assistant_2023-05-04T10-00-24.417Z.log](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/files/11396285/home-assistant_2023-05-04T10-00-24.417Z.log)

W panelu energia w HA ostatnie pełne dane mam z 11.03, a niepełne z 12.03.2023 - w eLiczniku mam te dane, więc to nie jest kwestia tego, że czegoś brakuje i nie może zaciągnąć :(

**Comment by PiotrMachowski** [comment]
Ok, to problem wygląda na to, że integracja słabo sobie radzi z dziurami w danych większymi niż 30 dni. Muszę zobaczyć, jak to mogę ogarnąć

**Comment by belkone** [comment]
Ok dzięki! jeśli jakoś mogę pomóc - coś jeszcze dostarczyć czy sprawdzić, daj proszę znać :)

**Comment by PiotrMachowski** [comment]
Ok, problem powinien być naprawiony w `v2.4.11`

**Comment by mmarcines** [comment]
Hej,

Puściłem aktualizacje do 2.4.11 i wszystko zadziałało jak należy.
Wyskoczyła mi jeszcze aktualizacja do Home Assistant core 2023.5.1 i po
zrobieniu aktualizacji HA integracja nie działa (integracja nie dostarcza
encji).


pt., 5 maj 2023, 02:39 użytkownik Piotr Machowski ***@***.***>
napisał:

**Comment by PiotrMachowski** [comment]
@mmarcines może Ci się limit logowań skończył?

**Comment by belkone** [comment]
@PiotrMachowski 
> Ok, problem powinien być naprawiony w `v2.4.11`

Piękne dzięki! po aktualizacji ruszyło i uzupełniło dane :) 

Mam jeszcze dwie dziury, przez które nie zgadza mi się zużycie - 26.03.2023 oraz 15.04.2023. Czy jest szansa jakoś zmusić integracje do dociągnięcia danych z tych dwóch dni, lub czy samoczynnie dociągnie je za jakiś czas? Dane w eLiczniku za te dni oczywiście są:

W logu natomiast wygląda to tak:
```
2023-05-05 10:50:56.673 DEBUG (SyncWorker_12) [custom_components.tauron_amiplus.connector] [<TUTAJ_PUNKT_POBORU>]: Downloading daily data for day: 14.04.2023, generation: False
2023-05-05 10:51:02.692 DEBUG (SyncWorker_12) [custom_components.tauron_amiplus.connector] [<TUTAJ_PUNKT_POBORU>]: Downloaded daily data for day: 14.04.2023, generation: False

2023-05-05 10:51:02.692 DEBUG (SyncWorker_12) [custom_components.tauron_amiplus.connector] [<TUTAJ_PUNKT_POBORU>]: Downloading daily data for day: 15.04.2023, generation: False
2023-05-05 10:51:07.771 DEBUG (SyncWorker_12) [custom_components.tauron_amiplus.connector] [<TUTAJ_PUNKT_POBORU>]: Failed to download daily data for day: 15.04.2023, generation: False

2023-05-05 10:51:07.771 DEBUG (SyncWorker_12) [custom_components.tauron_amiplus.connector] [<TUTAJ_PUNKT_POBORU>]: Downloading daily data for day: 16.04.2023, generation: False
2023-05-05 10:51:12.668 DEBUG (SyncWorker_12) [custom_components.tauron_amiplus.connector] [<TUTAJ_PUNKT_POBORU>]: Downloaded daily data for day: 16.04.2023, generation: False
```

W eLiczniku natomiast za przykładowy kwieceń, tak:
<img width="943" alt="Zrzut ekranu 2023-05-5 o 11 39 11" src="https://user-images.githubusercontent.com/14234849/236425110-35aafab6-b4a0-4789-890f-fb61017df312.png">

**Comment by PiotrMachowski** [comment]
@belkone prawdopodobnie w danych godzinowych dla tych dni brakuje części odczytów. Aktualnie integracja naprawia dane miesiąc wstecz, także jeśli wartości dla 15.04.2023 się pojawią do 15 maja, to zostaną naprawione. Dane za marzec raczej się już nie naprawią automatycznie, ale spróbuję dodać usługę do naprawiania danych rok w tył.

**Comment by belkone** [comment]
> @belkone prawdopodobnie w danych godzinowych dla tych dni brakuje części odczytów. 

Oczywiście masz racje, tak wygląda 15.04 godzinowo :) 
<img width="954" alt="Zrzut ekranu 2023-05-5 o 11 51 13" src="https://user-images.githubusercontent.com/14234849/236427695-3a073127-6cae-4a9b-88aa-ca881e266fd5.png">

> Aktualnie integracja naprawia dane miesiąc wstecz, także jeśli wartości dla 15.04.2023 się pojawią do 15 maja, to zostaną naprawione. Dane za marzec raczej się już nie naprawią automatycznie, ale spróbuję dodać usługę do wymuszenia naprawiania danych rok w tył.

Jeśli byłaby opcja wymuszania dociągnięcia brakujących danych byłoby pięknie! Bo te czasem lubią pojawiać w eLiczniku ze sporym opóźnieniem :<

**Comment by PiotrMachowski** [comment]
W `v2.4.12` dodałem usługę `tauron_amiplus.download_statistics` 👍

**Comment by belkone** [comment]
Super! Poczekam na uzupełnienie danych w eLiczniku i sprawdzę działanie, dzięki!:)
