### ISSUE TITLE
Błąd konfiguracji - object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by krzyzak44** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#137]
Po wgraniu v2.4.12 i restarcie mam błąd konfiguracji:

Error setting up entry eLicznik 5.......1 for tauron_amiplus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tauron_amiplus/__init__.py", line 58, in async_setup_entry
    await hass.services.async_register(service.domain, service.service, service.async_handle_service, service.schema)
TypeError: object NoneType can't be used in 'await' expression

**Comment by belkone** [comment]
@PiotrMachowski potwierdzam, u mnie to samo po restarcie i aktualizacji do 2.4.12

**Comment by Biegnik** [comment]
mam ten sam błąd i ten sam zapis w logu

**Comment by PiotrMachowski** [comment]
Dzięki, na razie wycofałem wersję v2.4.12, niedługo będzie poprawka

**Comment by Krzysztonek** [comment]
U mnie to samo:
![image](https://user-images.githubusercontent.com/87784133/236619919-d11708cc-00d5-4a6a-94fc-6f41db8ba241.png)
Wszyscy grzecznie czekamy na poprawkę ;)

**Comment by PiotrMachowski** [comment]
Naprawione w [v2.4.13](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.4.13)

**Comment by Krzysztonek** [comment]
Tak jest, śmiga aż miło! Dziękuje 🍺
