### ISSUE TITLE
brak odczytów licznika Tauron

### ISSUE THREAD

**Issue by salut1a** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#140]
Witam
Od jakiegoś czasu nie pobiera danych odczytu licznika z Tauron, wgrałem dzisiaj najnowszą wersję i nadal nie pobiera.

**Comment by PiotrMachowski** [comment]
Czy dane są widoczne na stronie eLicznik?
Czy coś jest w logach?
Konfiguracja przez Yaml czy przez UI?
Jaka wersja była zainstalowana wcześniej?

**Comment by salut1a** [comment]
- Tak dane są widoczne
- Tak:

Error requesting tauron_amiplus data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Yaml:
- platform: tauron_amiplus          
  name: Tauron
  username: !secret tauron_amiplus.username
  password: !secret tauron_amiplus.password
  energy_meter_id: !secret tauron_amiplus.energy_meter_id
  #check_generation: true
  monitored_variables: 
  .....................
- Wcześniejsza też nie działała ale nie wiem gdzie odczytać ?

**Comment by PiotrMachowski** [comment]
Ok, to proponuję usunąć konfigurację yaml, poczekać 2 dni i dodać od nowa, ale przez interfejs graficzny.

**Comment by salut1a** [comment]
Przerobiłem na UI i działa
serdecznie dziękuję ;)

**Comment by PiotrMachowski** [comment]
Super, dobrze, że się udało bez czekania
