### ISSUE TITLE
Magazyn Energi (wirtualny sensor)

### ISSUE THREAD

**Issue by asern1989** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#142]
Fajnie jakbyś bez ingerencji w configuration.yaml dodać wirtualny magazyn energi Tauron.

Tylko pytanie też czy dobrą masz metodę do obliczeń w README
state: "{{ (states('input_number.initial_energy_bank') | float(0) + states('sensor.tauron_amiplus_123_yearly_energy_generation') | float(0) * 0.8 - states('sensor.tauron_amiplus_123_yearly_energy_consumption') | float(0)) | round(3) }}"
        
a nie powinno być ... jak to tauron liczy, czyba ostatnie 12 miesięcy

state: "{{ (states('input_number.initial_energy_bank') | float(0) + states('sensor.tauron_amiplus_123_last_12_months_energy_generation') | float(0) * 0.8 - states('sensor.tauron_amiplus_123_last_12_months_energy_consumption') | float(0)) | round(3) }}"

**Comment by PiotrMachowski** [comment]
Wydaje mi się, że podejście z template sensorem i input numberem jest dość proste, a dodatkowo łatwo je dostosować do konkretnych potrzeb.

Osobiście nie jestem prosumentem, także nie wiem, jakie są konkretne reguły obliczania. Konfiguracja proponowana w README jest bazowana na tych dyskusjach: #57, #74. Jeśli istnieje jakiś dokument zawierający dokładny opis liczenia danych przez Tauron, to dostosuję konfigurację.

**Comment by tomasz-soltysik** [comment]
@PiotrMachowski Obecnie Tauron poza zwykłymi odczytami pobranej i oddanej energii, udostępnia dane zbilansowane. Jest to osobna zakładka w eLiczniku. To te wartości są potrzebne do obliczenia ilości energii, którą mamy "zmagazynowaną".
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/17692934/0b20aca2-b21d-4f32-847e-578ee8d9dec0)

Można też w zakładce energia wyświetlić wartości "normalne" i zbilansowane.
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/17692934/e8acf77e-31b1-464d-82be-616a9e90bfdb)
