### ISSUE TITLE
last_12_months_energy_consumption from tauron_amiplus has state class total_increasing, but its state is not strictly increasing

### ISSUE THREAD

**Issue by travnick** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#152]
Takie ostrzeżenie dzisiaj zobaczyłem no i w sumie racja, ta wartość nie będzie zawsze rosnąca. Bezsprzecznie rosnące będzie, póki nie minie pełny okres 12 miesięcy, ale następnie, jeżeli ktoś zacznie oszczędzać, to zużycie z ostatnich 12 miesięcy może maleć (w przypadku, gdy już wcześniej było zarejestrowane 12 miesięcy).

Analogicznie, żadna inna wartość, będąca sumą w danym oknie czasowym, nie może być określana jako rosnąca (zużycie dzienne, miesięcznie, kwartalne itp.)

```
Entity sensor.prad_rowna_last_12_months_energy_consumption from integration tauron_amiplus has state class total_increasing, but its state is not strictly increasing. Triggered by state 4427.662 (4440.659) with last_updated set to 2023-06-09T02:13:21.813117+00:00. Please report it to the custom integration author.
Entity sensor.prad_rowna_last_12_months_energy_generation from integration tauron_amiplus has state class total_increasing, but its state is not strictly increasing. Triggered by state 3920.729 (3924.562) with last_updated set to 2023-06-09T02:13:21.813730+00:00. Please report it to the custom integration author.
```

**Comment by PiotrMachowski** [comment]
Naprawione w wersji [v2.6.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.0)
