### ISSUE TITLE
AMIPlus API rate limiting

### ISSUE THREAD

**Issue by jarekgrzabel** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#155]
Miałem problem przez ostatnie 2 dni z pobieraniem metryk i zastanawiałem się czemu. Tauron zablokował mnie:
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/36036393/d743e998-f4ba-4994-977b-dbb5f36e5b90)
Wychodzi na to, że sposób pobierania danych przez dodatek wydaje się być zbyt agresywny. Nie wiem czy jest możliwość optymalizacji tego procesu.

Mam 2 liczniki z których zczytuję dane.

**Comment by PiotrMachowski** [comment]
Nie restartowałeś czasem HA kilka razy? Integracja loguje się 3 razy na dobę, także sama w sobie nie powinna powodować blokad konta

**Comment by jarekgrzabel** [comment]
Może i restartowałem kilka razy, ale wątpie żeby mnie wykopali po 2-3 restartach :). Ciekawe... chciałem do nich napisać, ale sam e-licznik nie ma w ogóle kontaktu technicznego.

**Comment by PiotrMachowski** [comment]
No to masz powód. Po reloadzie integracji (czyli też po restarcie HA) są 2 logowania. Masz 2 instancje, także 3 restarty to 12 logowań.
