### ISSUE TITLE
Bardzo długi start

### ISSUE THREAD

**Issue by melwinek** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#158]
Komponent bardzo długo uruchamia się. Jaki jest powód? Czy da się z tym coś zrobić?

**Comment by PiotrMachowski** [comment]
Startuje tak długo, bo pobiera dużo danych dzień po dniu (każdy dzień z osobona). Można to zmienić wyłączając niepotrzebne opcje w konfiguracji integracji.

**Comment by Jordan87** [comment]
Jesli mamy juz wczytane historyczne dane i zmienimy ustawienei aby wczytywal tylko ostatnie dni stare dane nie przepadną?

**Comment by PiotrMachowski** [comment]
Nie, dane są już w bazie HA

**Comment by Jordan87** [comment]
To w sumie jaki jest cel ich ponownego pobierania bo i tak luk chyba juz nie uzupelni? 26 marca z jakiegos powodu mi nie pobralo danych i tak zostal bez tego jednego dnia (e-licznik posiada juz dane dla tego dnia).

Swoja droga aby to naprawic pozostaje tylko czyszczenie i konfigurowanie od nowa?

**Comment by PiotrMachowski** [comment]
> To w sumie jaki jest cel ich ponownego pobierania bo i tak luk chyba juz nie uzupelni?

Integracja nie pobiera danych, jeśli nie ma takiej potrzeby. Potrzeba może być z dwóch powodów:
 - pobieranie danych historycznych (rok wstecz, tylko po dodaniu integracji)
 - jeśli w konfiguracji użytkownika jest ustawiony okres np roku

Dane automatycznie uzupełniane są miesiąc wstecz.

> Swoja droga aby to naprawic pozostaje tylko czyszczenie i konfigurowanie od nowa?

Jest do tego specjalna usługa: `tauron_amiplus.download_statistics`

[![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=tauron_amiplus.download_statistics)
