### ISSUE TITLE
Not issue - please contact

### ISSUE THREAD

**Issue by barcik75** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#16]
Hi,
I have some problem with configuration. Can we talk by mail? barcik@barcik.synology.me

**Comment by PiotrMachowski** [comment]
Hi,
You can find me in following places:
* [Home Assistant Polska](https://www.facebook.com/groups/homeassistantpolska) on Facebook
* [Home Assistant forum](https://community.home-assistant.io/u/3_14/)
* [AI-Speaker forum](https://ai-speaker.discourse.group/u/3.14)
* [Email](piotr.machowski.dev@gmail.com)
