### ISSUE TITLE
Energia configurable balans

### ISSUE THREAD

**Issue by andrzejkla** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#162]
Energia configurable balans nie resetuje się po roku czasu. 
![Screenshot_2023-10-03-18-26-28-200_io homeassistant companion android](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/94314930/8de2c7a8-d8a7-4deb-b8b1-4cb2dab2cbb6)

Pozostałe się zresetowała i naliczają dane od początku października.

**Comment by andrzejkla** [comment]
![Screenshot_2023-10-03-19-12-03-904_io homeassistant companion android](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/94314930/7ea9e721-d811-46e0-a9c0-626a9c757b55)

**Comment by andrzejkla** [comment]
![Screenshot_2023-10-03-19-15-41-830_io homeassistant companion android](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/94314930/d85b38ac-adbe-4933-ba32-28fcacb860d2)

**Comment by andrzejkla** [comment]
Teraz widzę że jednak żaden się nie zresetował. Czy należy datę na nowo ustawić w konfiguracji?

**Comment by PiotrMachowski** [comment]
> Czy należy datę na nowo ustawić w konfiguracji?

Dokładnie. W konfiguracji jest rok, który się automatycznie nie zmienia
