### ISSUE TITLE
Zablokowane konto Tauron

### ISSUE THREAD

**Issue by H3XXdev** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#167]
Hej,
Spotkał się ktoś z problemem zablokowanego konta przez używanie integracji?
Dzisiaj przestałem otrzymywać informacje w integracji więc myślałem że się wyrzuciła, usunąłem, dodałem na nowo i chcąc się zalogować na e-licznik otrzymałem informacje:

Przekroczono maksymalną liczbę logowań.
Ponieważ odnotowaliśmy znaczne przekroczenie liczby logowań, Twoje konto zostało tymczasowo zablokowane.
Prosimy o zalogowanie się za 8h, po tym czasie konto zostanie odblokowane.
Wcześniejsze logowanie się na konto spowoduje wydłużenie czasu odblokowania konta o kolejne 8h.

**Comment by PiotrMachowski** [comment]
Taka sytuacja może nastąpić np po kilkukrotnej rekonfiguracji integracji/restarcie HA. Nic na to nie mogę poradzić. Najlepiej wyłączyć integrację i spróbować włączyć po odblokowaniu konta.
