### ISSUE TITLE
Taryfa c12A

### ISSUE THREAD

**Issue by Raku2008** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#171]
Witam posiadam licznik w taryfie C12a i przy próbie logowania dostaje komunikat login to failed

**Comment by PiotrMachowski** [comment]
Czy w wersji [v2.6.0-beta](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.0-beta) licznik działa?

**Comment by PiotrMachowski** [comment]
Dodane w wersji [v2.6.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.0)
