### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by Lob0tomy** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#172]
Cześć,
Podczas dodawania urządzenia pojawia się błąd.
Podaje swój login oraz hasło, w oknie widzę swój licznik i wybieram go, ale gdy próbuję zatwierdzić pojawia się błąd "Failed to login".
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/128887126/dfb16956-2b07-4302-abd4-d4a3759a6ba1)

W logach pojawia się jedynie informacja:
2024-01-03 13:54:21.125 ERROR (MainThread) [custom_components.tauron_amiplus.config_flow] Failed to login

Wersja Home Assistant: 2023.10.1
Wersja integracji: V2.5.2

**Comment by Dukeskes** [comment]
Mam dokładnie to samo, rest jaki wychodzi to:
POST ./api/config/config_entries/flow/d35c823021aaeca8f280a2b2203134e4
payload energy_meter_id:  "100136661_60579396_7221412"

**Comment by Dukeskes** [comment]
Mam dokładnie to samo, logowanie śmiga, ale potem wybór punktu poboru to przychodzi cos takiego:


POST ./api/config/config_entries/flow/xxxx
payload: `{ energy_meter_id: "[xxx]" }`

response:
`{
    "type": "form",
    "flow_id": "[xxx]",
    "handler": "tauron_amiplus",
    "step_id": "select_meter",
    "data_schema": [
        {
            "selector": {
                "select": {
                    "options": [
                        {
                            "label": "[xxx]",
                            "value": "[xxx]"
                        }
                    ],
                    "multiple": false,
                    "sort": false,
                    "custom_value": false
                }
            },
            "name": "energy_meter_id",
            "required": true,
            "default": "[xxx]"
        }
    ],
    "errors": {
        "password": "server_no_connection"
    },
    "description_placeholders": {
        "error_info": "Failed to login"
    },
    "last_step": null,
    "preview": null
}`

**Comment by woodchuck84** [comment]
@PiotrMachowski: U mnie to samo. Jest wybór licznika, ale później sypie błędem Failed to login

**Comment by Dukeskes** [comment]
U mnie ruszyło, wygląda jakby problem był po stronie taurona

**Comment by PiotrMachowski** [comment]
Duplikat #165
