### ISSUE TITLE
Różnica w dziennym poborze oraz status encji nieznany

### ISSUE THREAD

**Issue by szymekkuwejt** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#174]
Witam.
Dzisiaj zmieniłem w panelu energia encje tak że pokazuje pięknie. Ten dzień co trzeba, godzinowo, wszystko się zgadza oprócz tego że energia nie jest sobie równa jak widać na poniższych screenach. Byłbym wdzięczny za wytłumaczenie czemu to tak jest.

![1](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/db276f1f-16ff-47f0-8378-65a7b988309b)
![2](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/3b3ddfe6-d3df-407f-8927-c38a8177ed8b)

No i na koniec z innej beczki, bo tyle klikałem, że położyłem dodatek encje status nieznany   a na końcu i tak przekroczyłem liczbę logowań i muszę czekać 8 godzin czy to ma coś wspólnego? Czy brakło mi cierpliwości i po prostu miałem czekać? Zauważyłem, że to się stało gdy zmieniłem konfiguracje na taką jak na screenie.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 5 stycznia 2024 23:34:59 (495 occurrences)
Last logged: 21:06:31

Platform tauron_amiplus does not generate unique IDs. ID tauron-5xxxxxxxxxxx37-generation_last_12_months already exists - ignoring sensor.tauron_amiplus_5xxxxxxxxxxxxxxx7_last_12_months_energy_generation

![3](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/37feda59-31ca-4fd6-a30d-a9b7ede5ccd4)

**Comment by PiotrMachowski** [comment]
Pokaż proszę konfigurację panelu energia.


> No i na koniec z innej beczki, bo tyle klikałem, że położyłem dodatek encje status nieznany a na końcu i tak przekroczyłem liczbę logowań i muszę czekać 8 godzin czy to ma coś wspólnego? Czy brakło mi cierpliwości i po prostu miałem czekać? Zauważyłem, że to się stało gdy zmieniłem konfiguracje na taką jak na screenie.

Każda zmiana konfiguracji integracji to ponowne logowanie. Tauron wprowadził dość niskie limity, nic na to nie poradzę. Trzeba poczekać

**Comment by szymekkuwejt** [comment]
> Pokaż proszę konfigurację panelu energia.
> 
> > No i na koniec z innej beczki, bo tyle klikałem, że położyłem dodatek encje status nieznany a na końcu i tak przekroczyłem liczbę logowań i muszę czekać 8 godzin czy to ma coś wspólnego? Czy brakło mi cierpliwości i po prostu miałem czekać? Zauważyłem, że to się stało gdy zmieniłem konfiguracje na taką jak na screenie.
> 
> Każda zmiana konfiguracji integracji to ponowne logowanie. Tauron wprowadził dość niskie limity, nic na to nie poradzę. Trzeba poczekać

![1](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/81be1d1a-ec8b-4889-aadf-ed41f64a9aeb)

![2](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/ead3bc4b-3403-47c1-916c-5fcb8e33050e)

nie może być to samo bo wtedy nie jest godzinowo tylko raz dziennie. Numery licznika na pewno są te same konto to same (nie mam innego).


Integracja już działa wyłączyłem na 9 godzin i po włączeniu działa.

**Comment by szymekkuwejt** [comment]
![3](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/3c975aac-5036-40d3-91a8-9dffc8e8b792)

![4](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/122492804/eca14a86-7276-4e7b-a9e2-10d07927c06d)

Teraz zauważyłem że nie ma paru godzin jeszcze pogrzebie nad innymi zużyciami w panelu energia bo mam ich tam dużo do wyboru a nie dokońca czytelne bo nazwy za długie ale tu już mówiłeś że na to nie masz wpływu

**Comment by szymekkuwejt** [comment]
Sorki za zamieszanie teraz widzę, że mam consumption dzień a nie mam noc... dodałem noc i się zgadza wszystko... Przepraszam jeszcze raz. PiotrMachowski Ty zamknij temat. Wielkie dzieło i działa pięknie.

**Comment by PiotrMachowski** [comment]
Co do robienia integracji, to tutaj powinieneś znaleźć info co i jak
https://developers.home-assistant.io/
