### ISSUE TITLE
ENERGY_KILO_WATT_HOUR

### ISSUE THREAD

**Issue by robertb1741** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#175]
Witam
Po aktualizacji w logach 
ENERGY_KILO_WATT_HOUR was used from tauron_amiplus, this is a deprecated constant which will be removed in HA Core 2025.1. 
Use UnitOfEnergy.KILO_WATT_HOUR instead, 
please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues

Pozdrawiam

**Comment by PiotrMachowski** [comment]
Naprawione w wersji [v2.6.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.0)
