### ISSUE TITLE
Odczyty nie aktualizują się

### ISSUE THREAD

**Issue by 3jam3** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#179]
Odczyty licznika nie są pobierane od dłuższego czasu. Ostatni dobowy odczyt jest sprzed 4 dni. Sprawdzałem w elicznik.tauron-dystrybucja.pl. Tam pełny, dobowy odczyt jest z wczoraj. Nie pomagają przeładowanie dodatku czy ponowna jego instalacja.

**Comment by 3jam3** [comment]
Odczyty są kompletne dla całego dnia, jeśli są. W logach jest to:
1.
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 03:39:28 (1 occurrences)
Last logged: 03:39:28

ENERGY_KILO_WATT_HOUR was used from tauron_amiplus, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues

2.
Logger: custom_components.tauron_amiplus.coordinator
Source: helpers/update_coordinator.py:318
integration: Tauron AMIplus (documentation, issues)
First occurred: 03:39:31 (2 occurrences)
Last logged: 03:39:43

Unexpected error fetching tauron_amiplus data: Too many login attempts
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 274, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 35, in update_method
    data = await self.hass.async_add_executor_job(self._update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 49, in _update
    return self.connector.get_raw_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/connector.py", line 120, in get_raw_data
    data.tariff = self.login()
                  ^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/connector.py", line 193, in login
    session, login_response = self.login_service(CONST_URL_LOGIN, CONST_URL_SERVICE)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tauron_amiplus/connector.py", line 183, in login_service
    raise Exception("Too many login attempts")
Exception: Too many login attempts

Kiedy próbuję się zalogować do licznika na stronie Tauronu, też wyświetla się komunikat o zbyt częstych próbach logowania.

**Comment by PiotrMachowski** [comment]
Najlepiej by było wyłączyć integrację na dobę i dopiero wtedy włączyć ponownie

**Comment by 3jam3** [comment]
Wpadłem na to i tak właśnie zrobiłem. W środku nocy minie 8 godzin. Swoją drogą, ciekawe co za geniusz wymyślił, że trwa to aż 8 godzin. Najważniejsze: dlaczego było tyle prób logowania?

**Comment by PiotrMachowski** [comment]
Każdy restart HA to nowe logowanie. Limity są dość niskie, więc stosunkowo łatwo je przekroczyć

**Comment by 3jam3** [comment]
Tyle, że ja nie restartowałem HA 30 razy, raz po razie. Jutro napiszę co się dzieje po przerwie w logowaniu.

**Comment by PiotrMachowski** [comment]
> Tyle, że ja nie restartowałem HA 30 razy, raz po razie.

A ile?

**Comment by 3jam3** [comment]
Nie więcej niż 4-4.

**Comment by 3jam3** [comment]
Po odczekaniu 8 godzin, udało się w końcu zalogować. Dane zostały pobrane. Dzisiejszych oczywiście nie ma. Wczorajsze w usłudze eLicznik są częściowe. WHA ich nie ma, przynajmniej na razie.
W dzienniku zdarzeń nie ma już wpisów o logowaniu. Wciąż jest ten wpis:
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 04:53:42 (1 occurrences)
Last logged: 04:53:42

ENERGY_KILO_WATT_HOUR was used from tauron_amiplus, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues

Pozdrawiam

**Comment by PiotrMachowski** [comment]
Ok, czyli wszystko działa poprawnie. Do HA pobierane są tylko pełne dni, także jak się dane pojawią na stronie, to zostaną pobrane.

Ten drugi error nie psuje na razie nic, jest zgłoszony osobno.

**Comment by 3jam3** [comment]
OK. Dzięki.
