### ISSUE TITLE
Add state_class to entieties

### ISSUE THREAD

**Issue by carlo497** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#18]
Hi, with new HA update we can configure "Energy" tab, but to do that sensors need to have state_class set to measurement. 

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
https://www.home-assistant.io/docs/energy/electricity-grid/

**Comment by PiotrMachowski** [comment]
I think I can add it, but please remember that daily sensor retrieves data for previous day, which probably makes it useless

**Comment by mmychu** [comment]
Hello, I join for request to add:
device_class: energy
state_class: measurement      
last_reset: '1970-01-01T00:00:00+00:00'

**Comment by mtyla** [comment]
Hi, I join also for the reguest:
device_class: energy
state_class: measurement
last_reset: '1970-01-01T00:00:00+00:00'

**Comment by Krzysztonek** [comment]
Hi, I'd love also to join for the reguest:
device_class: energy
state_class: measurement.
Would be very useful even if the sensors expose historical data from previous day. It will allow to see trends anyway :)
