### ISSUE TITLE
ENERGY_KILO_WATT_HOUR was used from tauron_amiplus

### ISSUE THREAD

**Issue by RhavoX** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#182]
Hej jest jeszcze jedno miejsce gdzie jest ENERGY_KILO_WATT_HOUR, #177 zdaję się to naprawiać.

Btw nie da się gdzieś wymusić konkretnych godzin synchronizacji? Pare restartów HA i dostałem 8h rate limitem od Tauronu ;/ nie chcialbym z banem na IP skonczyć przez nieuwagę.

**Comment by PiotrMachowski** [comment]
Fixed in [v2.6.1](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.1)
