### ISSUE TITLE
Pojedynczy słupek zamiast normalnego rozkłądu na wykresie

### ISSUE THREAD

**Issue by slawekmarczak** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#184]
Najnowsze wersje HA i wszystko inne aktualne (na poprzednich wersjcah cały czas to samo zachowanie było).
Kilka ostatni dni nie wyświetla sie poprawnie, a dalsze daty są ok, wyglaa to jak na załaczonych obrazkach. 
Co mozę być powodem? 
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/6f998623-8ca5-4dc3-b5e4-5ae08a114995)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/068b40ed-fe59-4990-9d09-c73bf1e8bbfb)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/559b2922-db90-4a87-9423-31454c3f9026)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/3f57241d-448d-4243-9003-7471ce7a1761)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/b0576fa1-79c2-4b84-aab4-cc797cce6c25)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/a121ee2b-8611-41bf-bdbb-3384bff33e21)

**Comment by PiotrMachowski** [comment]
Do panelu energia są dodane statystyki `tauron_importer`, czy encje?

**Comment by slawekmarczak** [comment]
> Do panelu energia są dodane statystyki `tauron_importer`, czy encje?

Encje, moze ich jest za dużo. Nie wiem jak  statystyki `tauron_importer` jeśli to jest lepsza metodą.
<img width="940" alt="image" src="https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/61077266/3dd4c85a-50d8-42c3-bf01-2431f4c8ce89">

**Comment by PiotrMachowski** [comment]
Musisz wybrać `tauron_importer` zamiast sensorów żeby mieć dane godzinowe
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/assets/6118709/53243140-02e6-4420-a869-b2a7df51d480)
