### ISSUE TITLE
Jednostka ENERGY_KILO_WATT_HOUR będzie deprecated

### ISSUE THREAD

**Issue by matfiz** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#185]
HA rzuca w logach: 

```
ENERGY_KILO_WATT_HOUR was used from tauron_amiplus, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'tauron_amiplus' custom integration
```
Stara jednostka jest jeszcze w pliku: [custom_components/tauron_amiplus/statistics.py](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/blob/3c58741118be92b9562b93d1c0b7f3b75ffbf770/custom_components/tauron_amiplus/statistics.py#L8)

**Comment by PiotrMachowski** [comment]
Fixed in [v2.6.1](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.1)
