### ISSUE TITLE
Kalkulacja kosztów

### ISSUE THREAD

**Issue by OskarLebuda** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#192]
Cześć! :)
Na wstępie chciałem zaznaczyć, że bardzo fajny projekt i gratulacje, za rozwiązanie :) 

Szukam odpowiedzi na pytanie czy w przypadku zastosowania `tauron_importer` jako wsadu do wykresu `Energy Dashboard` (tak, aby pokazywał konsumpcję godzinową) jest jakiś sposób, żeby policzyć koszty zużycia?  W przypadku wykorzystania importera, nie można użyć opcji `static price` ani `entity for current price`. Zastanawiam się czy to w ogóle jest do zrobienia? Jeśli nie to można od razu zamknąć issue :) 

![image](https://github.com/user-attachments/assets/2a4f3752-e13c-4c52-bcc0-bcba8799f654)

**Comment by PiotrMachowski** [comment]
Niestety aktualnie nie jest to możliwe
