### ISSUE TITLE
question about licence

### ISSUE THREAD

**Issue by araczkowski** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#2]
Hi Piotr @PiotrMachowski 

I'm asking behalf of AI-Speaker https://sviete.github.io/AIS-docs https://ai-speaker.com
We are thinking about possibility to add your Home-Assistant-custom-components-Tauron-AMIplus in our version of software as a standard integration available from application.

Of course we don't want to break the law and/or harm nobody feelings.
**That is why we are asking what do you think about this? What kind of licence you want to use for this code?**

Thanks and Regards
Andrzej

**Comment by PiotrMachowski** [comment]
Hi Andrzej,

I'm very glad you like my integration, I just have added a license to this repo.

Please be noted that usage of AMIplus is currently limited to 4 cities:
https://amiplus.tauron-dystrybucja.pl/amiplus-wroclaw/postep-wymiany/wroclaw
https://amiplus.tauron-dystrybucja.pl/amiplus-wroclaw/postep-wymiany/legnica
https://amiplus.tauron-dystrybucja.pl/amiplus-wroclaw/postep-wymiany/walbrzych
https://amiplus.tauron-dystrybucja.pl/amiplus-wroclaw/postep-wymiany/szklarska-poreba

Best regards,
Piotr Machowski
