### ISSUE TITLE
Integracja "not loaded" po updatecie do Core 2024.11.1

### ISSUE THREAD

**Issue by lakusz1github** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#200]
Integracja "not loaded" po updatecie do Core 2024.11.1

**Comment by tomekwl** [comment]
Zainstalowane na 2024.11.1. Pokazało dane po czym tak zamuliło system, że zerwało/zrywało połączenie sieciowe. Pomogło dopiero zablokowanie integracji z CLI i twardy restart hosta (samego HA nie dało się zresetować).
