### ISSUE TITLE
Z HA 24.12.2 integracja nie działa poprawnie ?!

### ISSUE THREAD

**Issue by GithubHomeA** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#201]
Dzień dobry, brak innych wpisów sugeruje, że to chyba moja konfiguracja jest wadliwa ?! W HA widać wprawdzie połączenie ( encje nie są wyszarzone ), ale w polach wartości albo 0,0 albo NaN; na backupowym Synology ( wersja HA 24.12 ) jest poprawnie. Jakaś sugestia ? Jakiś trop ? Restart, ponowny instalacja, config zrobione i nic. Dziękuję.

Komunikaty:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:234
First occurred: 14:24:43 (1 occurrences)
Last logged: 14:24:43

Detected code that calls async_forward_entry_setup for integration tauron_amiplus with title: eLicznik XXX and entry_id: YYY, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 14:23:43 (2 occurrences)
Last logged: 14:25:21

Detected that custom integration 'tauron_amiplus' calls async_forward_entry_setup for integration, tauron_amiplus with title: eLicznik XXX and entry_id: YYY, which is deprecated, await async_forward_entry_setups instead at custom_components/tauron_amiplus/__init__.py, line 54: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues
Detected that custom integration 'tauron_amiplus' sets option flow config_entry explicitly, which is deprecated at custom_components/tauron_amiplus/config_flow.py, line 232: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues

**Comment by GithubHomeA** [comment]
Dziękuję za odpowiedź, w tej chwili bana nie ma, appka w telefonie działa, komunikatu nie ma, w sobotę 2-gi NAS poprawnie zczytal dane drugiego PP.  Ban pojawił się ( zbieg okoliczności ? ) z chwilą dopisania kolejnego PP do HA ( na koncie są 3 ). W międzyczasie korespondowałem w TD dopytując o ilość dopuszczalnych zapytań do elicznika, info może przyda się innnym użytkownikom.

cyt.
Blokada nakładana jest po 30 logowaniach na konto. Co oznacza, że po zalogowaniu się, mogą Państwo sprawdzić wszystkie punkty (nawet jeśli byłoby ich 30 lub więcej) lub wykonywać inne działania w serwisie bezproblemowo. Ale jeśli w zbyt krótkim odstępie czasu zalogują się Państwo ponad 30 razy do serwisu, zostanie nałożona blokada. Zalecamy również nie zostawiać otwartej zakładki z eLicznikiem na komputerze przez dłuższy czas, ponieważ każde odświeżenie strony może być liczone jako kolejne logowanie.

**Comment by PiotrMachowski** [comment]
Fixed in [v2.6.1](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases/tag/v2.6.1)
