### ISSUE TITLE
KeyError: 'dane'

### ISSUE THREAD

**Issue by barpod** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#21]
Hi
I just installed this integration and it doesn't work for me. The reason is (copied from HA logs):

```
Logger: homeassistant.components.sensor
Source: custom_components/tauron_amiplus/sensor.py:170
Integration: Sensor (documentation, issues)
First occurred: 08:55:10 (6 occurrences)
Last logged: 08:55:34
tauron_amiplus: Error on device update!
```
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 212, in _update
    self.update_configuration()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 248, in update_configuration
    config = TauronAmiplusSensor.calculate_configuration(self.username, self.password, self.meter_id,
  File "/config/custom_components/tauron_amiplus/sensor.py", line 170, in calculate_configuration
    zones = json_data["dane"]["zone"]
KeyError: 'dane'
```

I played around this code a bit on my local machine and discovered that the problem exists for specific values of days_before variable:

days_before: 1
<Response [200]>
**KeyError('dane')**
days_before: 2
<Response [200]>
**KeyError('dane')**
days_before: 3
<Response [200]>
days_before: 4
<Response [200]>
days_before: 5
<Response [200]>
days_before: 6
<Response [200]>
days_before: 7
<Response [200]>
days_before: 8
<Response [200]>
days_before: 9
<Response [200]>

So in my case the problem is for the values 1 and 2, for values greater than 2 there is no problem and I can download the data from eLicznik,

**Comment by PiotrMachowski** [comment]
The problem is probably caused by a lack of data on eLicznik site, can you check it out?

**Comment by barpod** [comment]
This is the data I can see in elicznik:

![obraz](https://user-images.githubusercontent.com/19261523/131633564-f7125497-2c01-43ef-9587-3f53d4e168bc.png)

**Comment by PiotrMachowski** [comment]
Data for daily usage is retrieved from daily chart (in my case latest full data upload is from 28.08.2021)

**Comment by barpod** [comment]
Hmm, so what could be the solution? Playing around with days_before variable? Waiting for updated data in elicznik?

**Comment by PiotrMachowski** [comment]
Playing around with `days_before` doesn't make sense, as it would make integration return old data, additionally it could also be not enough if elicznik will not be updated.

Sooo, I think the only thing we can do is to wait :(
