### ISSUE TITLE
Reduce rate of logging in to prevent being blocked

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#23]
Currently integration is often blocked by exceeding a number of logins per day

**Comment by kwasiorrro** [comment]
Treshold for triggering captcha is about 100 login request per 24h

**Comment by PiotrMachowski** [comment]
@kwasiorrro thank you, that's good to know

**Comment by tomhash2** [comment]
Does changing MIN_TIME_BETWEEN_UPDATES to 3600 seconds will do?
Since sensor is getting its data for previous day it should be enough.

**Comment by PiotrMachowski** [comment]
@tomhash2 you can try to change `timedelta(hours=1)` in [const.py](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/blob/master/custom_components/tauron_amiplus/const.py) to something bigger, maybe it will work for you (for at leas 1 person it did not)

**Comment by Mr-Groch** [comment]
> timedelta(hours=1)

Thanks, timedelta(hours=4) worked for me and fixed this issue!

**Comment by PiotrMachowski** [comment]
Great!
I have published a new version (v2.0.4) that contains this change
