### ISSUE TITLE
More than one energy_meter_id

### ISSUE THREAD

**Issue by priv4** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#28]
Hi,

I have three counters, unfortunately the integration works only with one of them. How to construct an integration to show the values of all three different counters?

**Comment by PiotrMachowski** [comment]
Are you sure you have provided a correct meter id?

**Comment by priv4** [comment]
> Are you sure you have provided a correct meter id?

yes, 18 characters, and for example i enter id3, i only see id1 parameters

**Comment by kaweksl** [comment]
@priv4 By "integration works only with one of them" you mean all integrations shows same values despite different meter ids ?
If so you may look at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/pull/34

**Comment by PiotrMachowski** [comment]
Fixed in `v2.1.0`
