### ISSUE TITLE
Connection problem despite update 

### ISSUE THREAD

**Issue by nemezis336** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#29]
Cześć. Od niedawna pojawił się problem z encjami, po update tylko 2 raz intergracja pobrała dane, teraz nie chce się połączyć wogóle. Z czym może być problem?
Hi. Recently, there was a problem with entities, after the update, the integration downloaded data only twice, now it does not want to connect at all. What could be the problem?

![obraz](https://user-images.githubusercontent.com/59469300/134184116-c724167e-d728-4695-b7b6-b0a615351f63.png)

**Comment by nemezis336** [comment]
It works, I wonder if it's not the fault that I added readings to the energy module

**Comment by PiotrMachowski** [comment]
@nemezis336 Noo, I don't think so
