### ISSUE TITLE
Tauron Electricity Meter fails to update entities (become unavailable)

### ISSUE THREAD

**Issue by convicte** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#30]
Tauron Electricity Meter fails to update entities (all become unavailable), but a simple reload of the integration from the Integrations panel immediately bring is back to life and the entities pull the latest states down.

Please not restarting HA doesn't have this effect.

![image](https://user-images.githubusercontent.com/78666770/134196841-5a3a1ad5-1cfe-46f9-883b-45e8e6c5ece5.png)

This issue happens every 1-2 days.

If further information/logs are required, please let me know.

**Comment by PiotrMachowski** [comment]
Do you have the latest version of the integration?

**Comment by convicte** [comment]
Yes, I've installed it immediately upon release, 2 days ago.

Please note, the abovementioned behavior was identical in the prior version, as it is now.
The latest 'lock up' came earlier today, a few minutes prior to me posting this issue.

**Comment by PiotrMachowski** [comment]
Please try to follow steps from #29

**Comment by PiotrMachowski** [comment]
Does it work now?

**Comment by convicte** [comment]
Apologies for the late reply. I was unavailable for the last week.

Interestingly enough, I did absolutely nothing, and when I came back the issue was resolved.
There must be some problems with the API performance itself that lead to this.

Thank you again for the help!
I'll make sure to update the issue if the problem reoccurs.

**Comment by PiotrMachowski** [comment]
No problem :)
