### ISSUE TITLE
Daily consumption/generation not accessable in Energy tab

### ISSUE THREAD

**Issue by kkuriata** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#31]
Thanks for Energy tab integration!

Anyways, I don't see entities with `daily` consumption and generation (they are visible in entities registry, but not here).

![image](https://user-images.githubusercontent.com/2162679/134342769-3ecca562-389e-4d40-817c-4ac74d2e818d.png)

No issue with `monthly` and `yearly`.

**Comment by PiotrMachowski** [comment]
Data from daily entities is not suitable for energy tab, because they return values for a previous day

**Comment by tomkolp** [comment]
https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406

**Comment by tomkolp** [comment]
Jak to będzie działać? Dane z dnia poprzedniego będą widoczne w zakładce energia?

**Comment by PiotrMachowski** [comment]
![image](https://user-images.githubusercontent.com/6118709/213132132-c96b5aa5-ae13-4ce5-94ad-7cbf8abcf186.png)

Tak, dane godzinowe będą widoczne tylko w zakładce energia
