### ISSUE TITLE
Consumption, generation Total

### ISSUE THREAD

**Issue by nemezis336** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#32]
Cześć, czy jest możliwość zaciągnięcia z tauron i dodania tych encji ? Jest to potrzebne do obliczania rozliczenia rocznego w przypadku instalacji PV. W moim przypadku okres rozliczeniowy jest 1 rok i zaczyna się 05.10. Fajnie by było wiedzieć ile muszę dopłacić tauronowi za użycie prądu w przypadku posiadania instalacji PV

**Comment by PiotrMachowski** [comment]
Hej, nie jest to takie proste, bo używane przeze mnie "API" nie zwraca takich danych, bym musiał prasować HTMLa, na co niespecjalnie mam ochotę...

**Comment by nemezis336** [comment]
ok, rozumiem, może sam coś wymyślę jak sumować dane i je przeliczać, dzięki za fajnę integracje. Dobra robota

**Comment by PiotrMachowski** [comment]
Pewnie na podstawie encji yearly by się dało to zrobić
