### ISSUE TITLE
Energy meter missing daily consumption 

### ISSUE THREAD

**Issue by max1984** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#33]
For energy meter drop down list only monthly and yearly sensor shows up, missing daily. 
my core-2021.9.7

**Comment by PiotrMachowski** [comment]
Duplicate of #31

**Comment by PiotrMachowski** [comment]
I have changed approach and added importing data directly to statistics.
Since `v2.3.0` hourly readings are visible in Energy dashboard
