### ISSUE TITLE
Data not refreshing

### ISSUE THREAD

**Issue by lrybak** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#4]
Hi Piotr. First of all many thanks for such usefull integration!

I added integration recently. Today I found that fresh set of data are not fetched, while there are available on Tauron platform. Is there any way to shorten time between sensor update?

![image](https://user-images.githubusercontent.com/5631648/82867280-d806f980-9f2a-11ea-84dc-a885bd8efbcf.png)

![image](https://user-images.githubusercontent.com/5631648/82867270-d3dadc00-9f2a-11ea-9e1b-4f16bd7b4c17.png)

**Comment by PiotrMachowski** [comment]
Hi,

There are 2 factors that may cause this issue:
The first one is that consumption sensors refresh each hour, not every 30s to prevent IP banning and to not create unnecessary load on HA (Tauron updates data quite rarely).
The second one is that although data is present on the website the property `isFull` is still false. You can check it yourself by using browser's developer tool and looking for request to `https://elicznik.tauron-dystrybucja.pl/index/charts`.

**Comment by lrybak** [comment]
Hi, 
Agree, the refresh rate is reasonable. 
The sensors were refreshed at 10.40 this morning. You awaits the isFull=true flag while in the morning the data set were not flagged so.

All is perfect. Thank you
