### ISSUE TITLE
Taryfa g11 a g13

### ISSUE THREAD

**Issue by nemezis336** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#40]
Cześć, obecnie mam taryfę g11 i fajnie mi to liczy koszta w node red, ale chcę przejść na g13. Jest może w planach opanowanie taryfy g13?

**Comment by PiotrMachowski** [comment]
Hej, niewykluczone :D na razie niespecjalnie mam czas przysiąść do tej integracji, za dużo roboty gdzie indziej

**Comment by popis11** [comment]
> Hej, niewykluczone :D na razie niespecjalnie mam czas przysiąść do tej integracji, za dużo roboty gdzie indziej

Cześć. Fajnie by było jakbyś znalazł czas i zrobiłbyś integrację do g13. Pozdrawiam

**Comment by popis11** [comment]
[taryfy G11 G12W i G13  z cenami 2021 i 2022.xlsx](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/files/8358463/taryfy.G11.G12W.i.G13.z.cenami.2021.i.2022.xlsx)


Panie Piotrze może pomoże w zrobieniu AmiPlus dla G13

**Comment by gaszu** [comment]
Cześć!
Jakieś wolne moce przerobowe dla G13? Byłoby naprawdę super! Cała rodzina ma G13 i u wszystkich  mam HA z twoją integracją. Chętnie wspomogę twoją pracę, bo jest to dla mnie ważne.
