### ISSUE TITLE
Date of data

### ISSUE THREAD

**Issue by artupi** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#41]
Hi Piotr,
Can you add info on the date of readings. I'm comparing data from your addon with Tauron's app and I can see that energy usage is in my case 2 days old. When in app I open daily report, the app gives a message that data for yesterday is not complete and will change after next connection.
After switching to day before yesterday there's no such message.
Maybe there's also this kind of message through api.
In ami entities properties exists zone updated property but this date doesn't change.

Kind regards,

Artur

**Comment by ak6i** [comment]
+1.  Does the Tauron API expose the date of the data?

I'm trying to combine the energy usage from the Tauron API with data from my Solaredge installation on Home Assistant's energy dashboard, and since there is no timestamp on the data, the Tauron usage comes through a day later than my solar consumption.  This means the graphs don't line up.

**Comment by bglowacki** [comment]
Tauron provides the data from the previous day only, and it's not always the case - depending on whether it has full set of data or not.

From what I can see in the api it does provide date and hour in the response for the data that accessible.

**Comment by PiotrMachowski** [comment]
> Tauron provides the data from the previous day only, and it's not always the case

This problem makes daily sensors basically useless for HA applications at this moment

**Comment by dgrzeszczak** [comment]
Hej @PiotrMachowski , 

Jak się doda do grid consumption i generation miesięczne wartości z elicznika w dashoardzie energii to na to co od nich dostajemy to działa prawie idealnie. Jedyny problem jest z tym przesunięciem o jeden dzień przez elicznik. Czy dałoby się dorobić (może opcjonalnie) jakiś "offset" dla daty np w godzinach/dniach ? (albo checkbox "cofnij o 24h"). Dzięki temu raport byłby poprawny, oczywiście dla "today" byłby zawsze 0 ale zestawienie tygodniowe i miesięczne było by zgodne z rzeczywistością. 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/13122790/211086640-f04d1946-32c4-4885-b035-d3001d30fb7b.png">

**Comment by PiotrMachowski** [comment]
@dgrzeszczak nie sądzę żeby to było możliwe...

**Comment by dgrzeszczak** [comment]
@PiotrMachowski chyba rozumiem o co chodzi. Zerknąłem na docs'y - z góry sorry jeśli to nie ma sensu ale nie mam doświadczenia z programowaniem z HA i python.

Co myślisz o takim rozwiązaniu aby jako `state_class` użyć `total` ale manipulować `last_reset` i ustawiać go na dzień poprzedni względem odczytu. 

Tu https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-total dają przykład jak to działa. Oczywiście nie wiem jak to będzie się zachowywać z dashboardem energii ale w teorii to wygląda jak sposób do zaliczenia odczytu do odpowiedniego okresu. 

Btw tu https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes jest opisane, ze `state_class` `measurment` nie powinien być używany dla "yesterday's energy consumption" no ale domyślam się, że to było tak zrobione dla uproszczenia.

Nie wiem jakie dane z API dokładnie dostajesz ale jak pobiorę CSV z danymi to dostaje godzinową rozpiskę z odczytów. Może nawet tą datę można by użyć jako `last_reset ` ?

<img width="241" alt="image" src="https://user-images.githubusercontent.com/13122790/211148451-e78617a4-6aa4-4865-a620-24eae1a68347.png">

**Comment by PiotrMachowski** [comment]
@dgrzeszczak dodanie `last_reset` ciągle nic nie zmieni, bo HA dalej traktuje dane jako z aktualnego dnia

**Comment by dgrzeszczak** [comment]
@PiotrMachowski ok szkoda :( , dzieki za sprawdzenie. Niby taki prosty temat :)
