### ISSUE TITLE
Panel Energia

### ISSUE THREAD

**Issue by barii86** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#42]
Cześć, 
Mam problem z dodaniem Twojej integracji do panelu Energia w HA.

Dodaję Tauron AMIPlus consumption_daily do Użycia Energii w sekcji "Sieć Elektryczna" natomiast otrzymuję informację o błędzie:

**Brak danych o ostatnim resecie**
Następujące encje mają klasę stanu "measurement", ale brakuje danych o "last_reset":
sensor.tauron_amiplus_consumption_daily

Encje Tauron AMIPlus consumption_monthly oraz Tauron AMIPlus consumption_yearly nie powoduję błędu.

**Comment by PiotrMachowski** [comment]
Dane z sensora daily nie nadają się do panelu energia, bo dotyczą poprzedniego dnia

**Comment by Jordan87** [comment]
Nie da sie w zaden sposob tego tak skonfigurowac aby nastepnego dnia dodawal informacje o zuzycie dnia poprzedniego np o godzinie 24 (dnia poprzedniego, czyli uzupelnianie wczesniejszych luk)?

Wiem że panel energia normalnie bazuje na odczytach z danej godziny.

**Comment by PiotrMachowski** [comment]
Nie, nie da się aktualnie

**Comment by barii86** [comment]
Jak by Ci się udało, nie byłoby konieczności integracji dodatkowych narzędzi w Home Assistancie.

**Comment by PiotrMachowski** [comment]
![image](https://user-images.githubusercontent.com/6118709/213098068-f4d080f3-3c9d-4ccf-a267-cdb9131fabda.png)

**Comment by mmarcines** [comment]
@PiotrMachowski Do I understand correctly that in the Energy dashboard I should use those two: tauron_importer: consumption and tauron_importer: generation? If I choose anything else I'm getting a warning about "last_reset". If those two are correct - I've configured them yesterday in the energy dashboard and till now nothing is displayed.

**Comment by PiotrMachowski** [comment]
> Do I understand correctly that in the Energy dashboard I should use those two: tauron_importer: consumption and tauron_importer: generation? 

@mmarcines exactly. You can check logs for any errors

**Comment by mmarcines** [comment]
Only such warning appears in system - logs 
Logger: homeassistant.components.sensor
Source: runner.py:120
Integration: Sensor (documentation, issues)
First occurred: 12:26:32 (1 occurrences)
Last logged: 12:26:32
Setup of sensor platform tauron_amiplus is taking over 10 seconds.

**Comment by PiotrMachowski** [comment]
Which HA version do you have?

**Comment by mmarcines** [comment]
Home Assistant 2023.1.5
Supervisor 2023.01.dev1301
Interfejs użytkownika: 20230110.0 - latest

**Comment by PiotrMachowski** [comment]
Do sensors have correct values? Have you checked data from several days ago? Importer should import data starting from 01.01.2022

**Comment by mmarcines** [comment]
![image](https://user-images.githubusercontent.com/75376143/213435851-46680552-0656-4ce5-b395-ea6799d6bf12.png)
those displayed on the screenshot do have values but don't see import sensors on the list.

**Comment by PiotrMachowski** [comment]
They are not visible here, they are visible just in energy panel

**Comment by mmarcines** [comment]
![image](https://user-images.githubusercontent.com/75376143/213437860-63463025-8ce8-4339-99bc-37f4e9a27d9e.png)
so daily consumption do have some values (last 2 weeks). does it means that importer should work and energy dashoard should display something? any other suggestions what to check? 
![image](https://user-images.githubusercontent.com/75376143/213438508-0f251892-b894-4a2d-8fd3-f6bc9ca4f0bb.png)

**Comment by PiotrMachowski** [comment]
> does it means that importer should work and energy dashoard should display something? any other suggestions what to check?

Yes, importer is updated before sensors

You won't have data for today here, please check if it is available for e.g. 1 week ago

**Comment by mmarcines** [comment]
@PiotrMachowski right. My bad tauron is uploading data once a day (so have to look for periods in past). Like last week / month /year. 

![image](https://user-images.githubusercontent.com/75376143/213444625-eb295016-dcff-4109-953a-39db782a3e09.png)
![image](https://user-images.githubusercontent.com/75376143/213444718-57e019ca-3afa-4c52-aefe-8a0e3c45fd15.png)
