### ISSUE TITLE
last_reset missing

### ISSUE THREAD

**Issue by bernithiel** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#44]
![image](https://user-images.githubusercontent.com/26602041/156170988-bf9703f6-30b2-4156-9458-861515815c9d.png)

Die folgenden Entitäten haben die Zustandsklasse "measurement", aber "last_reset" fehlt:
sensor.tauron_amiplus_70756777_daily_energy_consumption
sensor.tauron_amiplus_70756777_daily_energy_generation

Question: How to get the "last_reset" manually added?

**Comment by pbabilas** [comment]
Got the same, need to use monthly and it shows only 2 measurements by day.

https://share.merce.com/files/jkZ2TGIh03.png

Any idea why daily not working?

**Comment by PiotrMachowski** [comment]
Data from "daily" sensors shouldn't be used in energy dashboard because it's offset by one day, so it's better to use monthly/yearly ones

**Comment by PiotrMachowski** [comment]
I have changed approach and added importing data directly to statistics.
Since `v2.3.0` hourly readings are visible in Energy dashboard

**Comment by bernithiel** [comment]
thx for info, but without "last_reset" data cannot be used in HA

[image: image.png]

*Bernd J. THIEL | *Private ***@***.***  | Mobile +48 5791 43328
<+48%205971%2043328>

Am Mi., 18. Jan. 2023 um 10:07 Uhr schrieb Piotr Machowski <
***@***.***>:

**Comment by bernithiel** [comment]
thx for info, but error not fixed

![image](https://user-images.githubusercontent.com/26602041/213181572-8db3fae3-3211-4d01-a476-26c90e2c4fe6.png)

**Comment by bernithiel** [comment]
ok,

xxx consumption in grid consumption
xxx production in return to grid
??? in solar production

*Bernd J. THIEL | *Private ***@***.***  | Mobile +48 5791 43328
<+48%205971%2043328>  | CH: Imbisbühlstrasse 109, 8049 Zürich


Am Mi., 18. Jan. 2023 um 14:20 Uhr schrieb Piotr Machowski <
***@***.***>:

**Comment by PiotrMachowski** [comment]
I think you can add XXX_generation to either "return to grid" or "solar production", but I'm not sure, as I don't have PV, so I haven't used this feature. You can always change it, so you can try both approaches

**Comment by bernithiel** [comment]
i see but data is not correct shown in HA

*in HA you have 3 Options and a House with PV need 5 Data*
from Grid to House # Tauron see
from PV to House # only PV / Smart Meter see
from House to Grid # Tauron see
  fyi, here Tauron dont see the "self consumption" it only see the diff
from Production - Self Consumption
from House (Self Usage) # only PV / Smart Meter see

can we make a Teamviewer Session that i can show you?

*Bernd J. THIEL | *Private ***@***.***  | Mobile +48 5791 43328
<+48%205971%2043328>  | CH: Imbisbühlstrasse 109, 8049 Zürich


Am Mi., 18. Jan. 2023 um 14:31 Uhr schrieb Piotr Machowski <
***@***.***>:

**Comment by PiotrMachowski** [comment]
Well, I can't generate data that Tauron doesn't have 😕 

> can we make a Teamviewer Session that i can show you?

Thanks, I think I understand it now
