### ISSUE TITLE
date is shift one day later.

### ISSUE THREAD

**Issue by pbabilas** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#45]
When I added integration to Energy dashboard, it has measurements , but it's shift one day. I know that tauron provide energy consumption one day past, but why its presented as actual day?

![ha](https://share.merce.com/files/ch3HcpNs6n.png)
![tauron](https://share.merce.com/files/uiM9JtK_Jr.png)

Is it possible to change date to correct one?

**Comment by PiotrMachowski** [comment]
No, currently it's not possible
