### ISSUE TITLE
Taryfa G12W

### ISSUE THREAD

**Issue by lukaszol** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#46]
G12 działa, ale G12W już nie.
Zmiana w const prawie jest ok, na tą chwilę pokazuje dwie strefy, ale:
daily_consumption:
zone1: 10.606
zone2: 6.789
day: 2022-03-18
generation: 24.433

daily_generation:
zone1: 10.606
zone2: 6.789
day: 2022-03-18
consumption: 17.395

są niepoprawne....
Może łatwo i szybko będzie zrobić wsparcie dla G12W? (tak, generation i consumption są odwrotnie, a sumy są złe...)

**Comment by PiotrMachowski** [comment]
Sama podstawa jest stosunkowo prosta, ale problemy tkwią w szczegółach - wykrywanie aktualnej strefy jest dość problematyczne

**Comment by robertfili** [comment]
A czy można by wyświetlać wskazania licznika?

**Comment by PiotrMachowski** [comment]
@robertfili #6
Raczej to problematyczne, bo danych tych nie ma w API, bym musiał wyciągać z HTMLa, co mi się średnio podobywuje

**Comment by robertfili** [comment]
/
a godzinowe zużycie energii?
zaznaczam że jestem zupełnym laikiem, pytam gdyż na stronie Taurona podają też godzinowe ...
Tak czy siak super integracja, wielkie dzięki!!
Pozdrawiam serdecznie
________________________________
Od: Piotr Machowski ***@***.***>
Wysłane: poniedziałek, 20 czerwca 2022 13:07
Do: PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus ***@***.***>
DW: robertfili ***@***.***>; Mention ***@***.***>
Temat: Re: [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus] Taryfa G12W (Issue #46)


@robertfili<https://github.com/robertfili> #6<https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/6>
Raczej to problematyczne, bo danych tych nie ma w API, bym musiał wyciągać z HTMLa, co mi się średnio podobywuje

**Comment by PiotrMachowski** [comment]
Nie, dane na stronie są aktualizowane raz dziennie, a HA aktualnie nie umożliwia pobierania danych historycznych

**Comment by robertfili** [comment]
przepraszam bardzo, dosłownie w tej chwili HA ponownie sczytał zużycie bez zmieniania niczego

pozdrawiam
________________________________
Od: Robert Robert ***@***.***>
Wysłane: piątek, 22 lipca 2022 14:16
Do: PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus ***@***.***>
Temat: ODP: [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus] Taryfa G12W (Issue #46)

Zmieniłem na taryfę G13 z G12w i teraz HA nie odczytuje zużycia.
Czy da się coś prosto zmodyfikować w pliku konfiguracyjnym w: custom-components/tauron_amiplus,  żeby działało?

Pozdrawiam i z góry dziękuję za pomoc
________________________________
Od: Piotr Machowski ***@***.***>
Wysłane: piątek, 24 czerwca 2022 12:05
Do: PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus ***@***.***>
DW: robertfili ***@***.***>; Mention ***@***.***>
Temat: Re: [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus] Taryfa G12W (Issue #46)


Nie, dane na stronie są aktualizowane raz dziennie, a HA aktualnie nie umożliwia pobierania danych historycznych

**Comment by mariusz-schimke** [comment]
> @robertfili #6
> Raczej to problematyczne, bo danych tych nie ma w API, bym musiał wyciągać z HTMLa, co mi się średnio podobywuje

Też mi się to nie podoba, ale nie wiem, czy jest inny sposób póki co, a ta dana by się przydała :). Nie wiem, czy jest ona jakkolwiek dostępna jest w response'ach, które już stosujesz do pobrania zagregowanego zużycia, ale poniższy request zwraca coś takiego:

`<div class="clear"></div>Pobór:<br /><span class="name"> <b></b> 02.10.2022 (23:59:59)</span>
<span original-title="Nr licznika: 12345678" class="value tipsyOnTop"> 000035</span><span class="unit">kWh </span><br />`

`POST https://elicznik.tauron-dystrybucja.pl/readings/getread`
z body x-www-form-urlencoded:
`day: 2022-10-02`

Można by zrobić jakieś wyciąganie regexem, chyba że są jakieś lepsze sposoby, np. sparsowanie tego HTML-a i wyciągnięcie wartości selectorem. Nie znam Pythona niestety i nie wiem, jakie możliwości daje ta technologia.

`<span +.*class=\".*value.*?\".*> *(\d+) *</span>`

Grupa pierwsza trafienia to stan licznika.

**Comment by PiotrMachowski** [comment]
@mariusz-schimke no niestety chyba masz rację, w danych które aktualnie pobieram nie ma tych wartości, także obawiam się, żę pozostaje to podejście, które proponujesz. Co do wyciągnięcia danych z HTMLa, to bym musiał się zastanowić, bo też się nie znam jakoś specjalnie na Pythonie ;)

**Comment by mariusz-schimke** [comment]
@PiotrMachowski, z dwa miesiące temu napisałem do Tauronu, czy można uzyskać dostęp do ich API, i dziś dostałem odpowiedź negatywną niestety. Zostaje więc chyba drapanie frontendu i aktualizacja paczki, jak coś się zmieni na stronie 😵‍💫.

**Comment by robertfili** [comment]
Zmieniłem na taryfę G13 z G12w i teraz HA nie odczytuje zużycia.
Czy da się coś prosto zmodyfikować w pliku konfiguracyjnym w: custom-components/tauron_amiplus,  żeby działało?

Pozdrawiam i z góry dziękuję za pomoc
________________________________
Od: Piotr Machowski ***@***.***>
Wysłane: piątek, 24 czerwca 2022 12:05
Do: PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus ***@***.***>
DW: robertfili ***@***.***>; Mention ***@***.***>
Temat: Re: [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus] Taryfa G12W (Issue #46)


Nie, dane na stronie są aktualizowane raz dziennie, a HA aktualnie nie umożliwia pobierania danych historycznych
