### ISSUE TITLE
Problem with daily readings

### ISSUE THREAD

**Issue by RadekLorenc** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#47]
Hi there
From couple of days i've some problem with integration (i thinh from time HA was updated to version 2022.3.X - before that everything was working fine). Daily readings showed in HA are incorrect (readings from one day are multiplied in couple of next days) and while login on tauron elicznik webpage i've message that daily login attemps was to high and i've to type in snapcha code to unlock entry

![screen_1](https://user-images.githubusercontent.com/85805905/159679073-a39b2abc-9ff5-40ea-ac14-7bc693a789c4.jpg)

**Comment by PiotrMachowski** [comment]
Fixed in `v2.1.0`
