### ISSUE TITLE
Sensors stopped updating, and the UI flow fails when reinstalling

### ISSUE THREAD

**Issue by convicte** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#48]
1) For the last 4-5 days the sensors would not update, and this was on both 2022.3 and 2022.4 HA versions
2) Having proceeded to recreate the sensors, the UI flow completely collapses upon providing correct credentials and server communication error is displayed.

![image](https://user-images.githubusercontent.com/78666770/162736554-87e6baae-84fd-4525-a9c8-ec1f9e46a04f.png)
![image](https://user-images.githubusercontent.com/78666770/162736626-99e44928-965a-4fc0-a03a-c0a14b5b6f53.png)

**Comment by convicte** [comment]
Yes, I can:
![image](https://user-images.githubusercontent.com/78666770/162747710-e8eb51cf-cbf5-426b-89b3-2033eb88095f.png)
Though, every time I log in I need to fill in a captcha picture request, due to 'excessive number of logins per day'.

Is it possible the plugin was bombarding the server with requests, which put up it's captcha preventive mechanism, which the plugin is not able to deal with?

**Comment by PiotrMachowski** [comment]
It shouldn't, but you can try disabling it, waiting 2 days and trying to add it again.

**Comment by convicte** [comment]
I was able to get the sensor recreated 15 min ago and it did take, though after pulling a few seconds of data for 1 entity, though it should have created several, it went into unavailable again:
![image](https://user-images.githubusercontent.com/78666770/163013037-08c0a217-04ee-4592-bcab-8c9dcf42b038.png)

Earlier today, I was able to log into the website without the captcha. As soon as I created the sensor, captcha was back with the 'too many requests' again.

**Comment by slodziak** [comment]
I am seeing exactly the same problem. Would appreciate any help, thank you!

**Comment by PiotrMachowski** [comment]
> I believe it's fair to assume the issue with the UI (above) is an indication of the captcha presence, hence resolving the excessive requests is probably where the focus should be.

You are correct. Integration receives unexpected response and throws an error, which is shown in UI. This error contains HTML, so it is rendered like on screenshots above

**Comment by convicte** [comment]
Happy to hear I am not too far off.

To this end, would you also agree the root cause is the exceeding of the Tauron approved number of requests per cycle?
Whether they changed the limit or the add-on went rouge requesting too often is to be seen, but it looks like as if this is the main problem resulting in all other manifestations of the issue.

Thank you in advance for any help and guidance!

**Comment by PiotrMachowski** [comment]
Yeah, this integration performs too many logins, which triggers captcha

**Comment by brambat** [comment]
I managed to overcome the issue by pulling only entities that I'm using in HA - see part of my confiig:
    monitored_variables:
#      - zone
#      - consumption_daily
#      - consumption_monthly
        - consumption_yearly
#      - generation_daily
#      - generation_monthly
        - generation_yearly
 It seems to be working fine for me for time beeng.

**Comment by convicte** [comment]
Would you mind explaining how you made changes to the add-on config?

From what I understood the yaml config was deprecated in response to the new UI flow. I don't know of ways to use the UI to limited entities updated?

Thanks in advance!

**Comment by convicte** [comment]
> Yeah, this integration performs too many logins, which triggers captcha

Any further thoughts on how to proceed?
Will you be taking any steps to fix the issue or should we seek other arrangements for the moment?

Thank you!

**Comment by brambat** [comment]
I'm not a "pro" in HA, I do have the latest HASSIO version, and Tauron-AMIplus addon in custom components where all configuration for it is in configuration.yaml - login, password, meter ID as well as listed monitored variables and there I hash all variables that I'm not monitoring ( consumption_yearly and generation_yearly I'm loking for), rest of the monitored variables are strarting with "#" so I belive addon is ignoring when pooling data (I'm not sure, maybe Piotr will confirm). Anyhow, that help me with to many request issue.

**Comment by PiotrMachowski** [comment]
Fixed in `v2.1.0`
