### ISSUE TITLE
Tauron API has become more restrictive

### ISSUE THREAD

**Issue by jonczykp** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#49]
It seems Tauron blocks API calls.
I was struggling with data update 2 weeks earlier and I disabled integration for 24 hours - it helped. If API was blocked you needed captcha when logging.

Now Integration is blocked again and see new message when logging to Tauron, so it seems Tauron changed policy again.. Is there a chance to adapt integration to new restirctions.

Informujemy, że odnotowaliśmy przekroczenie liczby możliwych logowań na Twoje konto, dlatego zostało ono tymczasowo zablokowane.
Dostęp zostanie automatycznie odblokowany po ośmiu godzinach.
Próby logowania się przed tym terminem będą powodowały wydłużenie okresu blokady o kolejne 8 godzin.
W przypadku pytań lub uwag, dotyczących opisanej sytuacji, prosimy o kontakt z naszymi Biurami Obsługi Klienta lub infolinią.

**Comment by PiotrMachowski** [comment]
This is not a good sign... I will check it out

**Comment by nbvcxz** [comment]
I can confirm it. Same here: Tauron website captcha with info about blocked access for 8 hours because of too many login attempts.

**Comment by pciechanowski** [comment]
> I can confirm it. Same here: Tauron website captcha with info about blocked access for 8 hours because of too many login attempts.

Nope. No captcha, żadnej captchy. Po prostu blokada.

**Comment by tj57** [comment]
Is it possible to add an option of how often to query the service? I was also blocked for 8 hours for frequent logins. A few times a day and just before midnight will be enough.

**Comment by paku2020** [comment]
Opcja ustawienia częstotliwości logowania też jest spoko, np po przecinku wpisać godziny.
Zazwyczaj wynik z całego poprzedniego dnia jest publikowany po południu więc wiecie.

Mnie też zablokowało na 8h :) A potrzebuję tylko raz dziennie pobrać wartość roczną

**Comment by PiotrMachowski** [comment]
To nie jest aż tak proste, muszę trochę przerobić integrację. Jestem gdzieś w połowie

**Comment by Adasadam** [comment]
> 

trzymam kciuki :)

**Comment by pciechanowski** [comment]
Ok, rzucę Wam zrobione na szybko i na odpierdol coś co nie rozwiąże problemu, a zmniejszy ryzyko blokad.
W integracji Tauron Amiplus wyłączacie odpytywanie o aktualizacje i tworzycie nową automatyzację, która będzie odpytywać encje. W edycji YAML automatyzacji wklejacie to co poniżej ewentualnie zmieniając nazwę tak by _IDENTYFIKATOR odpowiadało cyferkom w nazwach encji:
`alias: tauron data polling
description: ''
trigger:
  - platform: time_pattern
    hours: /12
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - sensor.tauron_amiplus_IDENTYFIKATOR_daily_energy_consumption
        - sensor.tauron_amiplus_IDENTYFIKATOR_daily_energy_generation
        - sensor.tauron_amiplus_IDENTYFIKATOR_monthly_energy_generation
        - sensor.tauron_amiplus_IDENTYFIKATOR_monthly_energy_consumption
        - sensor.tauron_amiplus_IDENTYFIKATOR_yearly_energy_consumption
        - sensor.tauron_amiplus_IDENTYFIKATOR_yearly_energy_generation
mode: restart`

**Comment by Adasadam** [comment]
> Ok, rzucę Wam zrobione na szybko i na odpierdol coś co nie rozwiąże problemu, a zmniejszy ryzyko blokad. W integracji Tauron Amiplus wyłączacie odpytywanie o aktualizacje i tworzycie nową automatyzację, która będzie odpytywać encje. W edycji YAML automatyzacji wklejacie to co poniżej ewentualnie zmieniając nazwę tak by `_IDENTYFIKATOR` odpowiadało cyferkom w nazwach encji:
> 
> ```yaml
> alias: tauron data polling
> description: ''
> trigger:
>   - platform: time_pattern
>     hours: /12
> condition: []
> action:
>   - service: homeassistant.update_entity
>     data: {}
>     target:
>       entity_id:
>         - sensor.tauron_amiplus_IDENTYFIKATOR_daily_energy_consumption
>         - sensor.tauron_amiplus_IDENTYFIKATOR_daily_energy_generation
>         - sensor.tauron_amiplus_IDENTYFIKATOR_monthly_energy_generation
>         - sensor.tauron_amiplus_IDENTYFIKATOR_monthly_energy_consumption
>         - sensor.tauron_amiplus_IDENTYFIKATOR_yearly_energy_consumption
>         - sensor.tauron_amiplus_IDENTYFIKATOR_yearly_energy_generation
> mode: restart
> ```
> 
> W skrócie - odpytywanie co 12 godzin. Ewentualnie wpiszcie wiecej jak chcecie.

end of the stream or a document separator is expected at line 1, column 3:
    []alias: tauron data polling
      ^

**Comment by b3cksy** [comment]
Super. Dam znać jutro czy się z automatu odblokowało.
ps.Też mam zablokowane. na 8 godzin + ewentualne dodatkowe 8.

**Comment by paku2020** [comment]
> Ok, rzucę Wam zrobione na szybko i na odpierdol coś co nie rozwiąże problemu, a zmniejszy ryzyko blokad. W integracji Tauron Amiplus wyłączacie odpytywanie o aktualizacje i tworzycie nową automatyzację, która będzie odpytywać encje. W edycji YAML automatyzacji wklejacie to co poniżej ewentualnie zmieniając nazwę tak by `_IDENTYFIKATOR` odpowiadało cyferkom w nazwach encji:
> 
> ```yaml
> alias: tauron data polling
> description: ''
> trigger:
>   - platform: time_pattern
>     hours: /12
> condition: []
> action:
>   - service: homeassistant.update_entity
>     data: {}
>     target:
>       entity_id:
>         - sensor.tauron_amiplus_IDENTYFIKATOR_daily_energy_consumption
>         - sensor.tauron_amiplus_IDENTYFIKATOR_daily_energy_generation
>         - sensor.tauron_amiplus_IDENTYFIKATOR_monthly_energy_generation
>         - sensor.tauron_amiplus_IDENTYFIKATOR_monthly_energy_consumption
>         - sensor.tauron_amiplus_IDENTYFIKATOR_yearly_energy_consumption
>         - sensor.tauron_amiplus_IDENTYFIKATOR_yearly_energy_generation
> mode: restart
> ```
> 
> W skrócie - odpytywanie co 12 godzin. Ewentualnie wpiszcie wiecej jak chcecie.

Jak w integracji wyłączyć odpytywanie? Jest do tego jakieś podmenu ? Nie mogę odnaleźć nic.

**Comment by pciechanowski** [comment]
> Jak w integracji wyłączyć odpytywanie? Jest do tego jakieś podmenu ? Nie mogę odnaleźć nic.

Konfiguracja -> urządzenia oraz usługi -> tauron amiplus i wyłączasz "Włącz odpytywanie o aktualizacje." (tak średnio zrozumiale przetłumaczyli)

**Comment by paku2020** [comment]
Oki to mam.
Ja dodawałem do pliku comfiguration.yaml  i dlatego nie miałem tego.
A mnie znów interesują tylko dane roczne.  Poczekam aż mi odblokują dostęp i zobaczmy :)

**Comment by jonczykp** [comment]
Cześć, dzięki a reakcje, zacząłem i wypadłem na tydzień, jak rozumiem na razie trzeba na automatyzacji, bo nie wiadomo kiedy nowa wersja. Trzeba więcej kawy dla Piotrka?

**Comment by paku2020** [comment]
Pisałem do tauronu dziś dostałem taką odpowiedz. Może to coś wniesie do integracji

`Zmieniliśmy proces logowania do eLicznika www- nie dotyczy aplikacji mobilnej. Klient po 30 logowaniu będzie miał zablokowane konto na 8h, czyli tymczasowo. Kolejne próby zalogowania przed upływem tego czasu będą wydłużać czas blokady o kolejne 8h. Licznik prób logowań również resetuje się co 8h
`
Wychodzi na to że 8h od ostatniego nieudanego logowania i po 30 logowaniach blokują.

**Comment by PiotrMachowski** [comment]
> Same issue as #48

Actually, same as: #35, #36, #38, #47 (probably) and #48

**Comment by b3cksy** [comment]
> Super. Dam znać jutro czy się z automatu odblokowało. ps.Też mam zablokowane. na 8 godzin + ewentualne dodatkowe 8.

Niestety encje dalej są unavailable

**Comment by paku2020** [comment]
> > Super. Dam znać jutro czy się z automatu odblokowało. ps.Też mam zablokowane. na 8 godzin + ewentualne dodatkowe 8.
> 
> Niestety encje dalej są unavailable

Automatyzacja działa gdy się ją wywołuje manualnie lub przy restarcie HA.
U mnie nie działa automatycznie. Może ktoś ją wyklika w Node-Red?  Ja próbowałem ale coś mi sie nie udaje. Mam małe doświadczenie z automatyzacjami

**Comment by PiotrMachowski** [comment]
Fix będzie opublikowany jeszcze dzisiaj. Aktualnie znajduje się na branchu `dev`

**Comment by PiotrMachowski** [comment]
Fixed in `v2.1.0`
