### ISSUE TITLE
Unable to connect with eLicznik

### ISSUE THREAD

**Issue by b3cksy** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#51]
I can connect via webpage to eLicznik but I cannot connect via HA.
I'm using newest version of your Tauron AMIplus integration.
![image](https://user-images.githubusercontent.com/102021737/165755451-1532fe1e-6d1f-4af7-a2d6-569c8b64aa88.png)

**Comment by PiotrMachowski** [comment]
Disable this integration for 12h, login to elicznik website and try to add integration again.

**Comment by b3cksy** [comment]
ok.

**Comment by b3cksy** [comment]
Still  the same issue accures.

**Comment by PiotrMachowski** [comment]
What is in logs?

**Comment by PiotrMachowski** [comment]
Fixed in v2.1.1
