### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by MyLittleGodziak** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#52]
While trying to add the eLicznik integration after updating to version 2.1.1, after providing valid credentials (integration was working with version 2.0.4, and broke with version 2.1.0). The only thing I'm seeing in the logs is this: 
![image](https://user-images.githubusercontent.com/52787208/166084977-c22c891b-41f3-411b-b09e-3b38780c82be.png)
which unfortunately doesn't say too much.

**Comment by PiotrMachowski** [comment]
This error should have been fixed in v2.1.1, are you sure you have it installed?

**Comment by MyLittleGodziak** [comment]
Correct. I've just double-checked, and the version that I have currently installed is in fact 2.1.1.

**Comment by PiotrMachowski** [comment]
I assume that you have restarted HA after upgrading?

**Comment by MyLittleGodziak** [comment]
Yep.

**Comment by MyLittleGodziak** [comment]
After a couple of days, I tried again to add the integration - this time everything worked. Not sure why, since I haven't restarted my HA instances since the last attempt, nor changed anything about my configuration. Since everything seems to work properly now, I'm gonna close this issue.

**Comment by PiotrMachowski** [comment]
Ok, somebody else included more detailed stacktrace and it turned out that I have forgot to remove one line in v2.1.1
