### ISSUE TITLE
cannot login to tauron server?

### ISSUE THREAD

**Issue by lukaszzyla** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#55]
stopped working after disabling and trying to re-enable the integration.
Cannot login to Tauron servers.
I deleted the integration because I started having issues with daily and monthly readings.
Daily was unavailable and monthly was incorrect.

**Comment by PiotrMachowski** [comment]
Have you tried logging in using website?

**Comment by lukaszzyla** [comment]
Yes, no problem to login in through web

Wysłano z Samsung w Plus
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lukaszzyla** [comment]
still no go....

**Comment by remigiuszp** [comment]
The same in my case. Login and password works directly via WWW and in E-licznik app, and does not work in
integration. Any ideas ?

**Comment by remigiuszp** [comment]
Sorry my fault. I made mstake durrin writing login name to password manager. It works :)

**Comment by PiotrMachowski** [comment]
@lukaszzyla does `v2.2.0` work for you?
