### ISSUE TITLE
A new feature for counting energy consumption

### ISSUE THREAD

**Issue by barcik75** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#56]
I tried to add the reading from your integration to the Energy dashboard as daily energy consumption. But I get this error:
```
No data on last reset
The following entities have status class "measurement" but data for "last_reset" is missing:
sensor.tauron_amiplus_xxxxxxxxxxxx_daily_energy_consumption
```
Is it possible to add this to make it work?
And a question, by the way. I noticed that the charts are not updated at 00:00 but at some random times. Is this normal behavior?

**Comment by PiotrMachowski** [comment]
Daily sensor is useless for energy meter, you should use monthly/yearly instead. 

Charts are updated whenever tauron decides to update data on their website

**Comment by PiotrMachowski** [comment]
I have changed approach and added importing data directly to statistics.
Since `v2.3.0` hourly readings are visible in Energy dashboard
