### ISSUE TITLE
Current readings

### ISSUE THREAD

**Issue by darth-aragoth** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#6]
Hi,
is it possible to add sensors with current readings of both meters (generation and consumption)? Tauron app can retrieve this information.

**Comment by PiotrMachowski** [comment]
Hi, this component uses data provided to draw graphs on the website, I will have to check if this data is retrieved in a readable way

**Comment by mariusz-schimke** [comment]
@PiotrMachowski, co myślisz o tym? https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/46#issuecomment-1265945398

**Comment by mariusz-schimke** [comment]
@darth-aragoth, I added reading the total meter value for consumption in [this](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/pull/65) pull request. I'm wondering if Tauron provides a similar value for generation. I have no idea about generation because I don't have photovoltaics or anything. Would you be able to show me a screenshot of how your eLicznik page looks if total generation is a separate counter than total consumption? Thanks!

**Comment by darth-aragoth** [comment]
@mariusz-schimke Tauron provides separate values for consumption and generation:
![Screenshot_20221106_091903](https://user-images.githubusercontent.com/72323164/200161224-3be508ac-9690-424a-9bed-ea3ad9a2e965.png)

**Comment by mariusz-schimke** [comment]
@darth-aragoth, thanks a lot!

I'll switch to Polish, but if you are an English speaker, please just let me know ;).

Żeby przygotować obsługę całkowitej produkcji energii, potrzebowałbym Twojej pomocy. Czy mógłbyś włączyć narzędzia dla developerów w przeglądarce i przekleić mi odpowiedź na zapytanie o stan na dzień? Gdybym to dostał, mógłbym doimplementować obsługę produkcji. W Chromie jest to menu Widok > Deweloper > Narzędzia dla deweloperów (inna opcja to kliknąć prawym przyciskiem na jakiś element na stronie, a potem opcja Zbadaj w menu. 

Potem przełączasz się do zakładek, które zaznaczyłem na czerwono. Gdy z ikony kalendarza w opcji Sprawdź stan na dzień wybierzesz jakąś minioną datę, w przeglądarce pojawi się odpowiedź na zapytanie `getread`. Gdybyś wysłał mi całą tę odpowiedź tutaj, będę miał co robić ;). Oczywiście możesz podmienić cyfry numeru licznika, czy cokolwiek, co będzie Cię tam identyfikowało, na wszelki wypadek. Dziękuję!!

![tauron](https://user-images.githubusercontent.com/28633575/200165088-632cd55f-e4fd-4e50-8617-c9f85ffa5d74.png)

**Comment by darth-aragoth** [comment]
@mariusz-schimke język polski w tym wątku raczej nie powinien być dla nikogo problemem :)

Mam nadzieję, że o to chodziło?

`<div class="clear"></div>Pobór:<br /><span class="name"> <b></b> 05.11.2022 (23:59:59)</span> <span original-title="Nr licznika: 73947060" class="value tipsyOnTop"> 015760</span><span class="unit">kWh </span><br /><div class="clear"></div><br />Oddanie:<br /><span class="name"> <b></b> 05.11.2022 (23:59:59)</span> <span original-title="Nr licznika: 73947060" class="value tipsyOnTop"> 021474</span><span class="unit">kWh </span><br />`

**Comment by darth-aragoth** [comment]
@mariusz-schimke myślę, że w tym wątku język polski nie będzie dla nikogo problemem :)

Mam nadzieję, że o to chodziło?
`<div class="clear"></div>Pobór:<br /><span class="name"> <b></b> 06.11.2022 (23:59:59)</span> <span original-title="Nr licznika: 12345678" class="value tipsyOnTop"> 015785</span><span class="unit">kWh </span><br /><div class="clear"></div><br />Oddanie:<br /><span class="name"> <b></b> 06.11.2022 (23:59:59)</span> <span original-title="Nr licznika: 12345678" class="value tipsyOnTop"> 021483</span><span class="unit">kWh </span><br />`

**Comment by mariusz-schimke** [comment]
Tak, dokładnie o to, dzięki serdeczne! :) Postaram się dostosować kod do obsługi generacji i dam Ci znać, jak będzie gotowe. Pozdrawiam

**Comment by mariusz-schimke** [comment]
@darth-aragoth, zapraszam do testowania, jeśli masz ochotę ;). [Tutaj](https://github.com/mariusz-schimke/Home-Assistant-custom-components-Tauron-AMIplus/tree/feature/total-consumption-support) znajduje się wersja obsługująca całkowity pobór i oddanie energii.

Jeśli chcesz ją przetestować, zrób sobie gdzieś na zewnątrz kopię swojego obecnego katalogu config/custom_components/tauron_amiplus (na wszelki wypadek), a potem usuń jego zawartość i wgraj tam wszystko, co znajduje się [tutaj](https://github.com/mariusz-schimke/Home-Assistant-custom-components-Tauron-AMIplus/tree/feature/total-consumption-support/custom_components/tauron_amiplus).

Następnie uzupełnij swoją obecną konfigurację tego add-onu o dwie dodatkowe opcje w sekcji `monitored_variables`:
- generation_total
- consumption_total.

Potem zrestartuj HA, wiadomo. W razie problemów, daj proszę znać.

Oczywiście będę wdzięczny za feedback. Dzięki!

**Comment by darth-aragoth** [comment]
Działa pięknie :) Dzięki, bardzo pomocna modyfikacja.

Będzie to się jakoś dało zintegorwać z głównym forkiem? Ewentualnie w HACS zasubskrybować ten fork?

**Comment by PiotrMachowski** [comment]
Będzie, bedzie, tylko muszę do tego usiąść, a ostatnio nie mam zbytnio czasu
