### ISSUE TITLE
Wykres godzinowy

### ISSUE THREAD

**Issue by sledzik1984** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#60]
Czy przy pomocy tego pluginu możliwe jest stworzenie w dashboardzie Energy w HA wykresu godzinowego takiego jak w apce Tauronu? 

![image](https://user-images.githubusercontent.com/1233199/196024603-b1c023dc-003f-4ab4-8fc2-60ffaf333e22.png)

**Comment by PiotrMachowski** [comment]
Nie, nie jest to możliwe. HA nie pozwala aktualnie na wgrywanie danych historycznych
