### ISSUE TITLE
Brak danych o ostatnim resecie

### ISSUE THREAD

**Issue by MariuszWoszczynski** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#61]
Ja mam taki problem po dodaniu wartości zużycia oraz generacji do zakladki Energia w HA:

![Screenshot_2022-10-16-13-39-49-970_org mozilla firefox](https://user-images.githubusercontent.com/115429759/196033412-712ec370-9e75-41ef-bcd3-2a582ff72daf.jpg)

O co chodzi?

**Comment by MariuszWoszczynski** [comment]
Ok, doczytałem ze te dane nie nadają się do panelu Energia, bo są z poprzedniego dnia. Ale dlaczego wartosci z poprzedniego dnia sie nie zgadzają? Przecież te dane maja chyba datę i o ile z dzisiaj nie widzę, to z wczoraj powinno chyba być ok

**Comment by PiotrMachowski** [comment]
To tak nie działa. Ale taki sam efekt osiągniesz używając sensorów miesięcznych bądź rocznych

**Comment by PiotrMachowski** [comment]
I have changed approach and added importing data directly to statistics.
Since `v2.3.0` hourly readings are visible in Energy dashboard
