### ISSUE TITLE
Add last_reset to the sensor entity

### ISSUE THREAD

**Issue by Mac-lucky** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#67]
The problem is if you want to use this integration in the Energy dashbaord. There is warning about missing attribute last_reset.
![obraz](https://user-images.githubusercontent.com/44085390/199974407-1a8c0918-645b-42a4-9e1c-88257fa678a1.png)

**Comment by PiotrMachowski** [comment]
Duplicate of: #31 #33 #42 #44 #56 #61

**Comment by Mac-lucky** [comment]
Sorry should use search before.

**Comment by PiotrMachowski** [comment]
I have changed approach and added importing data directly to statistics.
Since `v2.3.0` hourly readings are visible in Energy dashboard
