### ISSUE TITLE
Taryfa G11 - any plans?

### ISSUE THREAD

**Issue by edgardavim** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#69]
Hi Piotr,

I see few topics on this in Polish, but decided to have one in English (case others like me, struggle with harder topics in Polish).

Any idea of possible implementation for G11 ? With current electricity values it would be perfect addition in HA. 

thank you!

**Comment by PiotrMachowski** [comment]
G11 tariff is supported right now. Automatic zones detection is not supported for G11 because it doesn't have any zones ;)

**Comment by edgardavim** [comment]
I was reading and looks I am not lucky enough for having electronic reader :(

Kraków only in 2 years.

Then I guess no possibility to have such reading without changes in reader!
