### ISSUE TITLE
Pulling time

### ISSUE THREAD

**Issue by Vormillion** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#71]
Hi,

I can see that by default integration is pulling data every 12 hours and I'm fine with it as Tauron is refreshing data every 24 hours in application.

My question is - how can I set this integration to pull data every 12 hours but starting at 00:10 so I can have fresh data early morning? Right now it's pulling data around 13:00 which is too late.

**Comment by PiotrMachowski** [comment]
Are you sure that your data is available this soon? From my experience Tauron uploads it ~11:30

**Comment by Vormillion** [comment]
Hi,

I checked data this morning around 7 am and I already have data visible in elicznik webpage for 8th Jan.

**Comment by PiotrMachowski** [comment]
Was data complete? I have checked right now and I have only 00:00 - 18:00 for yesterday

**Comment by Vormillion** [comment]
Data is complete. Worth to mention that this night Tauron updated webUI and HA is not pulling new data anymore

**Comment by PiotrMachowski** [comment]
> Worth to mention that this night Tauron updated webUI and HA is not pulling new data anymore

Yes, I have noticed it as well
