### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#72]
Due to changes implemented in eLicznik website this integration is now broken

**Comment by PiotrMachowski** [comment]
An early version that adjusts this integration to new website is available at `dev` branch.

TODO:
- support for generation
- support for multiple meters

**Comment by manio** [comment]
Piotrze, dwa pytanka:
1. czy wiesz może czy to nowe API po zmianach udostępnia energię już zbilansowaną? (wartości kWh które podawał do tej pory eLicznik różniły się nieznacznie od tego co dostawaliśmy na fakturze - różnice wynikały podobno z tego że rozliczane było "po zbilansowaniu" a w eLiczniku nie było tego widać)
więcej info: https://www.elektroda.pl/rtvforum/topic3708224-1890.html
2. skąd masz te nowe endpointy/URLe? wyciągnięte z apk do androida? :)

**Comment by PiotrMachowski** [comment]
1. Ciężko powiedzieć, bo nie mam fotowoltaiki :) nie widziałem jeszcze jak wygląda pobieranie danych o wygenerowanej energii w nowej wersji systemu

2. Podejrzałem w przeglądarce, w trybie deweloperskim

**Comment by GrzesiuS** [comment]
Mogę pomóc z dostarczeniem danych odnośnie fotowoltaiki, tylko powiedz co potrzebujesz :)

**Comment by PiotrMachowski** [comment]
@GrzesiuS możesz zainstalować najnowszą wersję z [brancha `dev`](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/tree/dev), pobrać [dane diagnostyczne](https://www.home-assistant.io/integrations/diagnostics/) i mi je przesłać na `piotr.machowski.dev [at] gmail.com`

**Comment by manio** [comment]
Ad 2:
To jest mega ciekawe bo sam od początku to badam w Chrome i trybie developerskim i za żadne skarby nie potrafię namierzyć odwołań do tego API i tych URL które masz. Wszystki mam nadal do `.../charts`. Zaczynam się zastanawiać czy może to chodzi tylko o niektórych klientów? Albo sposób rozliczania netbilling/netmetering...

**Comment by manio** [comment]
Hehe... miałem po części rację. Okazuje się że aktualnie funkcjonują dwa serwisy. Cały czas pracowałem na tym starym (pewnie przez moje cookie przeglądarki) - w trybie incognito "na świeżo" moim oczom ukazała się całkiem inna (nowa) wersja strony - oraz odwołania do `api`!

**Comment by PiotrMachowski** [comment]
@manio no i wszystko jasne :D

**Comment by Vormillion** [comment]
Jest jakiś problem z energią zużytą na branchu dev.
Wczoraj wrzuciłęm wersję dev i poprawnie pobrało wartość 19.4 kWh.
Dzisiaj sensor dalej pokazuje mi 19.4 kWh a ostatnia aktualizacja sensora była 18 godzin temu - domyślnie powinno to chyba być 12 godzin więc coś nie zadziałało?

**Comment by Arekgor** [comment]
W jaki sposob moge zaninstalowac wersje z brancha dev? Probowalem dodac nowe niestandardowe repozytorium z nowym linkiem ale dostaje komunikat ze mam juz standardowa wersje. Można to jakoś sprawnie zrobic czy tylko poprzez podmiane poszczegolnych plikow ?
Dzieki

**Comment by PiotrMachowski** [comment]
@Vormillion Aktualnie integracja pobiera dane 2x dziennie, ale muszą być w danym momencie dane dostepne na stronie eLicznika. Wydaje mi się, że mogę zwiększyć częstotliwość odświeżania, wtedy zmiany zostaną wykryte wcześniej


@Arekgor trzeba ręcznie podmienić pliki

**Comment by Vormillion** [comment]
Niestety, licznik pokazywał ostatnią aktualizację 18 godzin temu i miał dane z 10 stycznia. Odświeżyłem teraz integrację ręcznie i od razu wpadło zużycie z wczoraj. Czy na szybko możesz mi powiedzieć, co zmodyfikować w lokalnych plikach żeby pobierać dane np. co 2 godziny? Może to kwestia mojego HA..

**Comment by PiotrMachowski** [comment]
@Vormillion pewnie by się zaktualizował za 6h. Pobierz najnowszą wersję, zmieniłem tam na aktualizację co 4h

**Comment by manio** [comment]
Panowie - a Wy macie dane świeższe niż dzień wstecz?
U mnie to działa tak że np. w okolicach 9-11 rano tauron wystawia dane za poprzedni dzień. Na chwilę obecną mam dane za wczoraj (w dodatku często przełom dnia w okolicach północy jest niekompletny i kolejne ładowanie dopiero potrafi załatać tę różnicę).

**Comment by PiotrMachowski** [comment]
@manio dokładnie tak samo. Wczoraj jeszcze o 18 były niekompletne

**Comment by mmarcines** [comment]
Jakies 2h temu wrzucilem dev wersje i mam dane ze wczoraj. @PiotrMachowski  czy jesli w eliczniku Licznik energii
pobranej pokazuje wartosc z polnocy (dnia wczorajszego) 11.01.2023 23:59:59  to czy aktualizowanie co 4h zmieni tutaj cokolwiek? Current_meter_reading = produkcja z ostatniego dnia (z północy)
Druga kwestia na dev nie mam informacji zwiazanej z energy generation. 

![current_meter_reading](https://user-images.githubusercontent.com/75376143/212044446-11c6b8ca-1bb7-4939-841a-f2cbce53c0ad.jpg)
![daily_gen](https://user-images.githubusercontent.com/75376143/212044448-4861c4f7-f0ca-4539-a022-59a8f7f1e18b.jpg)
![licznik_energii_pobranej](https://user-images.githubusercontent.com/75376143/212044450-91f09189-305e-4cbc-abbc-20f2db078b27.jpg)
![monthly_gen](https://user-images.githubusercontent.com/75376143/212044454-de6fd6e6-ffcf-4a22-8562-34d10d479b47.jpg)
![tauron](https://user-images.githubusercontent.com/75376143/212044455-8b167c09-efdf-4645-b0d6-6abbc5c114d7.jpg)
![yearly_gen](https://user-images.githubusercontent.com/75376143/212044460-86f7294e-a626-46ce-bc7c-4a4d63ace3b5.jpg)

**Comment by mmarcines** [comment]
Wczytałem dev wersje. Pobiera dane o konsumpcji. Niestety generation ma status unknown. U kogoś działa zbieranie informacji o produkcji? 
![tauron](https://user-images.githubusercontent.com/75376143/212046322-9cc6159e-747f-4391-9edf-41efe5fbe38a.jpg)
![yearly_gen](https://user-images.githubusercontent.com/75376143/212046323-b76cae5c-eef0-434c-989c-d5acd59748be.jpg)
![daily_gen](https://user-images.githubusercontent.com/75376143/212046316-d5890488-c3e1-48ce-8be9-495938d8cb66.jpg)
![monthly_gen](https://user-images.githubusercontent.com/75376143/212046321-6f914910-a933-4429-9dc7-bf2b12a7a386.jpg)

**Comment by convicte** [comment]
Czy jest plan, aby obecny `dev` wyszedł jako wersja Beta, zanim nie zostanie wypuszczony w ostatecznej wersji.
Nie bardzo mogę usunąć wersję `v2.1.3` przed instalacją `dev` ponieważ popsuje to wiele sensorów i wizualizacji.

Na ten moment natywna instalacja z UI HACS nie prezentuje nic powyżej 2.1.3.
![image](https://user-images.githubusercontent.com/78666770/212055277-617662fb-1771-4019-89b9-b4af4677b96d.png)

Z góry dziękuję za wyjaśnienie!

**Comment by PiotrMachowski** [comment]
@mmarcines pewnie dlatego, że jeszcze nie zaimplementowałem obsługi danych o produkcji ;) Możesz mi przesłać swoje [dane diagnostyczne](https://www.home-assistant.io/integrations/diagnostics/) na piotr.machowski.dev [at] gmail.com.

@convicte nie musisz nic usuwać, wystarczy, że podmienisz pliki i zrestartujesz HA. Zobaczę, co się da zrobić z releasem wersji dev

**Comment by convicte** [comment]
@PiotrMachowski serdeczne dzięki za szybką odpowiedz.

Podmienisz = pobranie repo `dev` i wkopiowanie folderu do istniejącej struktury w HA?
![image](https://user-images.githubusercontent.com/78666770/212057898-34ee2d9d-8f66-48b8-b06a-854636794e98.png)

Na pewno zwiększy to testowalność nowych wersji, jeżeli tworzenie i wypuszczanie `dev` jako bety poprzez HACS nie jest dużym problemem. 
Jeżeli uda mi się zainstalować obecny `dev` to również może przesłać logi dla produkcji - mamy dzisiaj piękny słoneczny dzień z 4kW nadprodukcji na 8kWp.

**Comment by PiotrMachowski** [comment]
> Podmienisz = pobranie repo dev i wkopiowanie folderu do istniejącej struktury w HA?

Dokładnie. Doszedł też plik `diagnostics.py`, także nie wystarczy podmiana zawartości dotychczasowych plików

**Comment by convicte** [comment]
> @mmarcines pewnie dlatego, że jeszcze nie zaimplementowałem obsługi danych o produkcji ;) Możesz mi przesłać swoje [dane diagnostyczne](https://www.home-assistant.io/integrations/diagnostics/) na `piotr.machowski.dev [at] gmail.com`.


Przesłałem pliki diagnostyczne razem z produkcją na podany email.

Byłoby świetnie, jeżeli udałoby się dorzucić ten PR - https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/pull/65 w nadchodzących wersja.

Pozdrawiam!

**Comment by PiotrMachowski** [comment]
@convicte dzięki! 

> Byłoby świetnie, jeżeli udałoby się dorzucić ten PR - #65 w nadchodzących wersja.

Ten PR jest już nieaktualny przez zmianę interfejsu. Dodałem tą funkcję w wersji `dev` - powinieneś mieć encję "current_readings"

**Comment by convicte** [comment]
OK, rozumiem!

Mam:
![image](https://user-images.githubusercontent.com/78666770/212073922-7c2d6fb8-2f26-4d33-a2cd-790a1e31a245.png)

**Comment by PiotrMachowski** [comment]
Wrzuciłem wersję `v2.2.0-beta.1` (jest dostępna w HACS), potencjalnie powinna obsługiwać również produkcję. Poproszę o przetestowanie @GrzesiuS @mmarcines @convicte

**Comment by convicte** [comment]
Zainstalowałem powyższą betę chwilę temu, ale na razie pomimo odświeżenia produkcja jest niedostępna:
![image](https://user-images.githubusercontent.com/78666770/212091701-66bcc0a3-e866-478e-9d12-28f2af31e851.png)

Dam znać, jeżeli pojawiłaby się później.

**Comment by PiotrMachowski** [comment]
@convicte możesz jeszcze raz mi przesłać dane diagnostyczne?

**Comment by convicte** [comment]
Definitywnie działa lepiej kiedy znajduje się w repo... ;)

![image](https://user-images.githubusercontent.com/78666770/212102982-fac5e12c-4f5a-4bb4-a7ed-ba3cd4b4947a.png)

Uznałbym sprawę za rozwiązaną, ale lepiej, jeżeli jeszcze kilka osób sprawdzić, dla pewności.

Serdeczne dzięki za wkład!!

**Comment by PiotrMachowski** [comment]
Wartości prawidłowe?

**Comment by prezes210** [comment]
Sprawdziłem na `v2.2.0-beta.2` potwierdzam poprawne wartości dla `generation_daily` `consumption_daily`.
Na chwilę obecną wszystko wydaje się działać.
Dzięki za szybkiego fixa :)

**Comment by Vormillion** [comment]
Co ciekawe próbowałem dodać właśnie integrację od nowa - pojawia się błąd:

TauronAmiplusConnector.get_raw_values_daily() missing 1 required positional argument: 'generation'

**Comment by Arekgor** [comment]
U mnie to samo nie moge sie zalogowac przy dodawaniu nowej integracji

**Comment by PiotrMachowski** [comment]
@Vormillion spróbuj odinstalować i zainstalować ponownie

**Comment by mmarcines** [comment]
a ja sobie poczekam trochę ..... 
Miałem wersje DEV ... Potem wgrałem beta (i przy beta już nie działało mi logowanie). Sprawdzę jutro rano zatem.
![image](https://user-images.githubusercontent.com/75376143/212123546-8e864fb3-712d-4e73-b27f-814f376bef00.png)

**Comment by PiotrMachowski** [comment]
@Vormillion @Arekgor naprawione w `v2.2.0-beta.3`, dzięki!

**Comment by Arekgor** [comment]
Wszystko działa, wydaje się że jest OK. 
Jesli to nie problem, mozna tez dodac encje "current meter reading" dla generation?

**Comment by Vormillion** [comment]
@PiotrMachowski - wszystko działa pięknie :) Dzięki!

**Comment by PiotrMachowski** [comment]
@Arekgor a jest takie coś widocznego w eLiczniku?

**Comment by Arekgor** [comment]
@PiotrMachowski tak, analogicznie do "current meter reading" dla poboru jest tez licznik dla generation. Jest to wartosc kumulacyjna ktora notabene pojawia sie na fakturze jako podstawa rozliczenia. 
![Bez tytułu](https://user-images.githubusercontent.com/120714074/212171232-2d8338d2-d21a-4ed2-a235-122e60b2a673.jpg)

**Comment by PiotrMachowski** [comment]
@Arekgor dodane w `v2.2.0-beta.4`, dzięki za sugestię

**Comment by convicte** [comment]
> @Arekgor dodane w `v2.2.0-beta.4`, dzięki za sugestię

![image](https://user-images.githubusercontent.com/78666770/212202719-7142e376-0a94-4768-8e8b-81719b1da3b5.png)
Działa!

**Comment by convicte** [comment]
> @PiotrMachowski 
> >dodane w `v2.2.0-beta.4`, dzięki za sugestię
> 
> ![image](https://user-images.githubusercontent.com/78666770/212202719-7142e376-0a94-4768-8e8b-81719b1da3b5.png) Działa!

**Comment by PiotrMachowski** [comment]
W wersji `v2.2.0-beta.5` dodałem obliczanie bilansu godzinowego, byłbym wdzięczny za sprawdzenie, czy wartości się zgadzają

**Comment by Arekgor** [comment]
Dzieki, u mnie wszystko działa.

**Comment by convicte** [comment]
Mogę potwierdzić, że pojawiają się 2 nowe liczniki bilansowe dla dnia i miesiąca, ale ktoś, kto liczy to sobie na piechotę w wątku (#57) musiałby potwierdzić czy liczby się zgadzają.

**Comment by mmarcines** [comment]
@PiotrMachowski jak dla mnie wartości się zgadzają (daily i monthly balance zgadza się z tym co jest w eliczniku).
A skoro już tak nam sprawnie idzie ;) to może jeszcze jeden enhancement https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/74 ?

**Comment by mm84** [comment]
Panowie - sypie mi błędem - IOnvalid config for [sensor.tauron_amiplus]: [check_generation] is an invalid option for [sensor.tauron_amiplus]. Check: sensor.tauron_amiplus->check_generation. (See ?, line ?).

**Comment by PiotrMachowski** [comment]
@mm84 tak, usunąłem tą opcję z konfiguracji, teraz polegam tylko na `monitored_variables`

**Comment by mm84** [comment]
> @mm84 usunąłem tą opcję z konfiguracji, teraz polegam tylko na `monitored_variables`

to co mam zmienić w configu? Usunąć check_generation: true? Jak usunę to:

Invalid config for [sensor.tauron_amiplus]: value must be one of ['balanced_daily', 'balanced_monthly', 'consumption_daily', 'consumption_monthly', 'consumption_reading', 'consumption_yearly', 'generation_daily', 'generation_monthly', 'generation_reading', 'generation_yearly'] @ data['monitored_variables'][0]. Got 'zone'. (See ?, line ?).

**Comment by convicte** [comment]
> > @mm84 usunąłem tą opcję z konfiguracji, teraz polegam tylko na `monitored_variables`
> 
> to co mam zmienić w configu? Usunąć check_generation: true? Jak usunę to:
> 
> Invalid config for [sensor.tauron_amiplus]: value must be one of ['balanced_daily', 'balanced_monthly', 'consumption_daily', 'consumption_monthly', 'consumption_reading', 'consumption_yearly', 'generation_daily', 'generation_monthly', 'generation_reading', 'generation_yearly'] @ data['monitored_variables'][0]. Got 'zone'. (See ?, line ?).

Użyj konfiguracji przez UI, jeżeli i tak odczytujesz wszystkie zmienne?

**Comment by PiotrMachowski** [comment]
@mm84 zone też usunąłem. [Tu masz dokumentację](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/tree/dev)

**Comment by mm84** [comment]
@PiotrMachowski  Dziękuję!

**Comment by PiotrMachowski** [comment]
Czy ktoś widzi jakieś problemy w logach? Jeśli nie, to chyba można uznać, że wszystko jest gotowe na release

**Comment by convicte** [comment]
Przez cały dzień od czasu instalacji  `v2.2.0-beta.5` pojawił się tylko jeden niegroźny log, prawdopodobnie podczas jednego z restartów HA:

![image](https://user-images.githubusercontent.com/78666770/212320456-051a0abc-13d7-4e76-bd03-490c0c7ed92a.png)

Oprócz tego cisza!

**Comment by mmarcines** [comment]
U mnie od 6ciu godzin tez cisza w logach (v2.2.0-beta.5).

**Comment by convicte** [comment]
Ja musiałem niestety wyłączyć integrację, bo przekroczyłem limit zapytań.

Muszę odczekać pewnie 12-24 godziny.

**Comment by piecyk57** [comment]
> > @mm84 usunąłem tą opcję z konfiguracji, teraz polegam tylko na `monitored_variables`
> 
> to co mam zmienić w configu? Usunąć check_generation: true? Jak usunę to:
> 
> Invalid config for [sensor.tauron_amiplus]: value must be one of ['balanced_daily', 'balanced_monthly', 'consumption_daily', 'consumption_monthly', 'consumption_reading', 'consumption_yearly', 'generation_daily', 'generation_monthly', 'generation_reading', 'generation_yearly'] @ data['monitored_variables'][0]. Got 'zone'. (See ?, line ?).

Witajcie. W tym przypadku należy usunąć konfigurację 'ami' z pliku config. Zrobić Restart HA, wkleić i ponowny restart HA.

**Comment by mm84** [comment]
Ja całkowicie usunąłem z configu i HACS. A następnie dodałem przez przycisk 

[https://camo.githubusercontent.com/637fd24a458765d763a6dced4b312c503f54397bdd9b683584ef8054f305cd7f/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f636f6e6669675f666c6f775f73746172742e737667] Klik

**Comment by PiotrMachowski** [comment]
@piecyk57 przecież napisałem wyżej, co trzeba zrobić...

@convicte dużo razy restartowałeś HA?

**Comment by convicte** [comment]
> @convicte dużo razy restartowałeś HA?
Pewnie 4-5 razy dzisiaj.
Czasem nie wracały odczyty sensorów dla liczników, więc 2 razy wyłączyłem i włączyłem integracje.

Musiałem przesadzić w ten sposób.

**Comment by grest** [comment]
Hej, a działa Wam poprawnie wybieranie punktu poboru? Próbuje każdej z 3 wartości - to co widać na stronie, to co jest w html jako value oraz nr płatnika - nic z tego nie działa prawidłowo :|

**Comment by PiotrMachowski** [comment]
@grest nie, nie miałem od nikogo odpowiednich danych testowych 
Issue #54

**Comment by PiotrMachowski** [comment]
Potrzebowałbym info o zapytaniach, jakie idą przy zmianie punktu poboru.

Sądzę, że issue #54 będzie wystarczające, bo w praktyce sprowadza się do tego samego problemu

**Comment by gkozlowski-git** [comment]
Czy jest jakaś szansa na wyciągnięcie danych w podziale na dzień/noc. Konkretnie chodzi mi o taryfę G12w.

**Comment by PiotrMachowski** [comment]
Dane o strefach są w atrybutach

**Comment by gkozlowski-git** [comment]
Dzięki, wystarczyło sprawdzić/poszukać, a nie pytać tak od razu. Wszystko jest i jest super .
