### ISSUE TITLE
Wyświetlanie miesięcznych odczytów

### ISSUE THREAD

**Issue by Vormillion** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#75]
Cześć,

Temat nie związany ściśle z samą integracją, chociaż zastanawiam się czy miesięczny odczyt pobierany jest codziennie i codziennie wartość miesięczna przyrasta?

Czy komuś z was udał się wyświetlać statystyki miesięczne w apexchart-cards?

**Comment by PiotrMachowski** [comment]
> czy miesięczny odczyt pobierany jest codziennie i codziennie wartość miesięczna przyrasta?

Dokładnie
