### ISSUE TITLE
Przekroczona maksymalna liczba logowań do eLicznik

### ISSUE THREAD

**Issue by Jordan87** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#79]
Hej

Jak czesto na ostatniej wersji loguje sie do platformy?
Wlasnie probowalem wejsc przez przegladarke na eLicznik i zobaczylem komunikat
![image](https://user-images.githubusercontent.com/10414918/212983004-b72c10b3-fe3f-464c-ba37-98d622e75914.png)

Dzis wrzucilem najnowsza wersje 2.2.0

**Comment by PiotrMachowski** [comment]
Co 8.5h. Restartowałeś HA kilka razy?

**Comment by mmarcines** [comment]
Wczoraj wieczorem też chciałem wrzucić v 2.2.0 (miałem dev) i ujrzałem ten sam komunikat. Dziś rano wrzuciłem wersje 2.2.0 i w ciągu dnia restartowałem HA 3x w przeciągu 10 minut i póki co jestem w stanie się zalogować.

**Comment by Jordan87** [comment]
Raz na pewno poszedl restart przy aktualizacji dodatku, raz restartowany przy aktualizacji HA, chyba wiecej nie bylo. Po ilu logowaniach blokują?

**Comment by PiotrMachowski** [comment]
@Jordan87 nie mam pojęcia

**Comment by Jordan87** [comment]
Narazie nie bede wylaczal i bede obserwowal temat.

**Comment by Jordan87** [comment]
W innych godzinach pobiera miesieczne i w innych dzienne statystyki?
![image](https://user-images.githubusercontent.com/10414918/213150039-3deac0b9-3d5a-4009-9c7b-32e5e3482b4c.png)

**Comment by Jordan87** [comment]
Poczekał bym kilka dni czy problem nie bedzie wracal. jesli nie zamkniemy :)

Jak czesto dodatek probuje pobierac dane z eLicznika i od czego jest to zalezne?

**Comment by PiotrMachowski** [comment]
Sorry, napisałem odpowiedź, ale zapomniałem wysłać.

Integracja pobiera dane co 8.5h, a oraz przy:
- każdym restarcie HA
- zmianie konfiguracji
- wywołaniu opcji "Wczytaj ponownie"
- wygenerowaniu danych diagnostycznych


Czy mogę już zamknąć issue?

**Comment by mattPiratt** [comment]
Na wstępie pragnę pogratulować wspaniałych osiągnięć z tym modułem, w ostatnim tygodniu. Dzięki za tą ciężką pracę.

W temacie zamknięcia tego issue, pozwolę sobie zasugerować aby umieścić tego typu opis: w jakich okresach sie pobiera dane...  gdzieś w miejscu jakimś, by w przyszłości inni użytkownicy mogli łatwo ją znaleźć. Ja sam miałbym kłopot gdyby to issue nie było dziś jeszcze otwarte z zawartymi wyjaśnieniami. 

Serdecznie pozdrawiam

**Comment by PiotrMachowski** [comment]
> Na wstępie pragnę pogratulować wspaniałych osiągnięć z tym modułem, w ostatnim tygodniu. Dzięki za tą ciężką pracę.

Mam nadzieję, że to koniec prac nad tą integracją, przynajmniej na jakiś czas 😄 

Jaki kłopot masz na myśli?

**Comment by mattPiratt** [comment]
> Jaki kłopot masz na myśli?
Wybaczcie jeśli wyraziłem się niejasno. Miałem na myśli to że komentarze z tej dyskusji były dla mnie bardzo pomocne. Idę dla wielu innych odwiedzających są. Dzięki nim wiedziałem że problem logowania się nie jest wyłącznie moim problemem a rzeczą która dotyczy wszystkich. Opis tłumaczący jakich przedziałach czasu moduł czyta dane z strony eLicznik jest również bardzo pomocny. Z tąd moja sugestia by zawrzeć takie informacje/ ostatnia w pliku README.

**Comment by Jordan87** [comment]
@PiotrMachowski Jesli chcesz mozesz zamknac. W razie potrzeby się go otworzy ale chyba nie ma zbyt częstego logowania. Jedyna niewiadoma to na ile moja ograniczenie ustawione.
