### ISSUE TITLE
Konfiguracja nieprawidłowa po ostatniej aktualizacji

### ISSUE THREAD

**Issue by GregoryKowalik** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#80]
Cześć,

po ostatniej aktualizacji występuje problem z konfiguracją wtyczki:

Konfiguracja nieprawidłowa!

Invalid config for [sensor.tauron_amiplus]: [check_generation] is an invalid option for [sensor.tauron_amiplus]. Check: sensor.tauron_amiplus->check_generation. (See ?, line ?).

Wersja wtyczki: 2.2.0
Wersja HA: core-2023.1.5

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/releases
Wystarczy usunąć

**Comment by GregoryKowalik** [comment]
Super, działa, dzięki bardzo.
