### ISSUE TITLE
Invalid statistic_id po updacie do v2.3.0

### ISSUE THREAD

**Issue by matix2120** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#82]
Cześć, po updacie z 2.1 na 2.3 nie pobierają mi się żadne dane. Restartowałem HA kilka razy, usunąłem integrację z HA i skonfigurowałem na nowo (w GUI), dalej tak samo. 

Wersja HA 2023.1.5, supervisor 2022.12.1. 
Poniżej log z błędem: 

> Logger: custom_components.tauron_amiplus.coordinator
> Source: components/recorder/statistics.py:2035 
> Integration: Tauron AMIplus ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues)) 
> First occurred: 11:39:23 (5 occurrences) 
> Last logged: 11:45:01
> 
> Unexpected error fetching tauron_amiplus data: Invalid statistic_id
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/tauron_amiplus/coordinator.py", line 26, in _async_update_data
>     await self.generate_statistics(data.consumption.json_month_hourly, False)
>   File "/config/custom_components/tauron_amiplus/coordinator.py", line 32, in generate_statistics
>     await update_statistics(self.hass, self.meter_id, generation, data, self.connector)
>   File "/config/custom_components/tauron_amiplus/statistics.py", line 67, in update_statistics
>     async_add_external_statistics(hass, metadata, statistic_data)
>   File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 2035, in async_add_external_statistics
>     raise HomeAssistantError("Invalid statistic_id")
> homeassistant.exceptions.HomeAssistantError: Invalid statistic_id

Daj proszę znać jeśli mogę coś jeszcze zrobić u siebie lub potrzeba więcej info.

**Comment by matix2120** [comment]
Dodałem integrację jeszcze raz zwracając na to uwagę, ale nic się nie zmieniło. Zresztą nie dotykałem konfiguracji dopóki nie zobaczyłem błędu w log, a ogólnie na poprzedniej wersji wszystko działało ok.

**Comment by PiotrMachowski** [comment]
To jest nowa funkcja, której nie było w poprzedniej wersji integracji. Mógłbyś pokazać swoje ID/nazwy encji? Jeśli nie tu, to na maila `piotr.machowski.dev [at] gmail.com`

**Comment by matix2120** [comment]
Podesłałem na maila

**Comment by PiotrMachowski** [comment]
Ok, wszystko jasne, zaraz wleci fix

**Comment by PiotrMachowski** [comment]
Zobacz proszę v2.3.1

**Comment by matix2120** [comment]
Działa, dzięki wielkie! Żeby tak szybko komercyjny support w niektórych firmach odpowiadał jak Ty... :)

**Comment by PiotrMachowski** [comment]
Super!
Może gdyby też udostępniali efekty swojej pracy za darmo... 😜
