### ISSUE TITLE
Entities "not available"

### ISSUE THREAD

**Issue by karaspr** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#9]
For couple of days all entities connected with component are not available. Of course no change has bedd made in configuration. Any clue what is happening? All eLicznik entities are even gone from "entities" panel in HA...

**Comment by karaspr** [comment]
already solved. https://forum.arturhome.pl/t/integracja-tauron-e-licznik/341/14

**Comment by PiotrMachowski** [comment]
Nothing has to be edited, yesterday I have published an update that contains a fix (not only this change was required)
