### ISSUE TITLE
last_12_months_balance from integration tauron_amiplus has state class total_increasing, but its state is negative

### ISSUE THREAD

**Issue by mmg1t** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#98]
Home Assistant 2023.1.7 (ostatnia dostepna stabilna)
Frontend 20230110.0 - latest

git clone AMIplus zrobiony jakies 2h temu,

w logach HomeAssistanta pojawia sie co jakis czas (zgłaszam, bo m.in. jest o to prośba w logach):

`2023-01-28 00:50:10.279 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.tauron_amiplus_XXXXXXXXXXXXXXXXXX_last_12_months_balance from integration tauron_amiplus has state class total_increasing, but its state is negative. Triggered by state -1165.472 with last_updated set to 2023-01-27T23:44:59.999999+00:00. Please report it to the custom integration author.
`

**Comment by PiotrMachowski** [comment]
Fixed in `v2.4.6`

**Comment by mmg1t** [comment]
warning juz sie nie pojawia, super!

PS. cos zle robie bo caly czas mam:
Tauron energy bank : Unavailable
Wpisalem do configuration.yamla tresc ktora jest w sekcji "How to calculate available energy as a prosument?" readme... potem dodalem sensor w daszbordzie ... ale jest Unavailable.

PS.2
configurable_balance mam w tysiącach ujemną wartość ... poprawnie ? (nadprodukcja?)

**Comment by PiotrMachowski** [comment]
A poprawiłeś wszystkie ID encji?

Co do balansu to zobacz ten wątek:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/57

**Comment by mmg1t** [comment]
bingo! (eh te literówki;) )

PS.1
pokazuje dziwnie małą wartość ... kilkaset tysiecy kilo...Z lektury #57 rozumiem ze liczenie pt. "co pokazuje portal jako wygenerowane -minus- zużyte  * 0,8" .. to nie jest poprawne rozumowanie?..
Czy te rozliczenia godzinowe to jest pobierane przez API ? ... bo wydaje mi sie ze tam trzeba "zamawiać raport" by dostac takie dane w jakims CSV ...

PS.2
co to jest "initial_energy_bank"  - na jaką wartość należy to ustawić ?

**Comment by PiotrMachowski** [comment]
1. Nie do końca się znam na temacie, bo nie mam fotowoltaiki. Rozliczenia godzinowe są pobierane z API przeznaczonego do generowania wykresów na stronie eLicznika.
2. Tutaj powinieneś ustawić ilość energii jaka Ci przeszła z poprzedniego okresu rozliczeniowego. Więcej info tu: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/74
